-- GENERATED by scripts/gen_save_load.py -- do not edit by hand.
-- Re-run it after changing the schema of any saved table.
--
-- Both functions are single CedarScript bodies, and a function
-- call is one transaction: a failure part-way through rolls the
-- whole save or load back, verified under autocommit as well as
-- inside an explicit BEGIN. So a torn save cannot be observed.

CREATE OR REPLACE FUNCTION doom_save_game(p_slot integer, p_map_id integer, p_player_thing_id integer, p_skill integer, p_name text) RETURNS integer
LANGUAGE cedarscript AS $doom$
DELETE FROM save_slots WHERE slot=p_slot::int;
INSERT INTO save_slots (slot,saved_at,name,map_id,player_thing_id,map_name,skill)
SELECT p_slot::int, NOW(), p_name::text, p_map_id::int,
       p_player_thing_id::int,
       (SELECT m.name FROM maps m WHERE m.map_id=p_map_id::int),
       -- The skill the WORLD was built with, taken from
       -- level_stats rather than the caller. reset_stage seeds
       -- thing_health/monster_ai per skill, so a save that
       -- recorded a different skill than its own world loaded
       -- with monsters that had no health and no AI row: they
       -- rendered alive, never attacked, and cost frame time.
       COALESCE((SELECT ls.skill_bit FROM level_stats ls
                  WHERE ls.map_id=p_map_id::int
                    AND ls.player_thing_id=p_player_thing_id::int),
                p_skill::int);

DELETE FROM save_player_state WHERE slot=p_slot::int;
INSERT INTO save_player_state (slot,map_id,player_thing_id,health,alive,level_tics,previous_x,previous_y,position_x,position_y,base_z,view_z,view_angle,momentum_x,momentum_y,bob_strength,previous_view_z,previous_view_angle,sector_id,pain_face_tics,armor,armor_class,backpack,ammo_bullets,ammo_shells,ammo_rockets,ammo_cells,key_blue,key_yellow,key_red,radsuit_tics,invis_tics,momentum_z,damage_count,bonus_count,light_amp_tics,power_map,god_mode,noclip,invuln_tics,berserk,message,message_tics,frags,death_tics,killer_id,sprite_frame)
SELECT p_slot::int,map_id,player_thing_id,health,alive,level_tics,previous_x,previous_y,position_x,position_y,base_z,view_z,view_angle,momentum_x,momentum_y,bob_strength,previous_view_z,previous_view_angle,sector_id,pain_face_tics,armor,armor_class,backpack,ammo_bullets,ammo_shells,ammo_rockets,ammo_cells,key_blue,key_yellow,key_red,radsuit_tics,invis_tics,momentum_z,damage_count,bonus_count,light_amp_tics,power_map,god_mode,noclip,invuln_tics,berserk,message,message_tics,frags,death_tics,killer_id,sprite_frame FROM player_state WHERE map_id=p_map_id::int;

DELETE FROM save_player_weapons WHERE slot=p_slot::int;
INSERT INTO save_player_weapons (slot,map_id,player_thing_id,current_weapon,pending_weapon,state,seq_index,tics,flash_seq_index,flash_tics,sx,sy,shot_serial,fired_this_tick)
SELECT p_slot::int,map_id,player_thing_id,current_weapon,pending_weapon,state,seq_index,tics,flash_seq_index,flash_tics,sx,sy,shot_serial,fired_this_tick FROM player_weapons WHERE map_id=p_map_id::int;

DELETE FROM save_player_weapon_owned WHERE slot=p_slot::int;
INSERT INTO save_player_weapon_owned (slot,map_id,player_thing_id,weapon_id)
SELECT p_slot::int,map_id,player_thing_id,weapon_id FROM player_weapon_owned WHERE map_id=p_map_id::int;

DELETE FROM save_things WHERE slot=p_slot::int;
INSERT INTO save_things (slot,id,map_id,x,y,z,angle,spawn_x,spawn_y,spawn_angle,mom_x,mom_y,type,flags)
SELECT p_slot::int,id,map_id,x,y,z,angle,spawn_x,spawn_y,spawn_angle,mom_x,mom_y,type,flags FROM things WHERE map_id=p_map_id::int;

DELETE FROM save_thing_health WHERE slot=p_slot::int;
INSERT INTO save_thing_health (slot,map_id,thing_id,health,max_health,alive)
SELECT p_slot::int,map_id,thing_id,health,max_health,alive FROM thing_health WHERE map_id=p_map_id::int;

DELETE FROM save_monster_ai WHERE slot=p_slot::int;
INSERT INTO save_monster_ai (slot,map_id,thing_id,state,state_tics,seq_index,sector_id,attack_cooldown,fired_this_tick,target_thing_id,charge_tics,movedir,movecount)
SELECT p_slot::int,map_id,thing_id,state,state_tics,seq_index,sector_id,attack_cooldown,fired_this_tick,target_thing_id,charge_tics,movedir,movecount FROM monster_ai WHERE map_id=p_map_id::int;

DELETE FROM save_monster_projectiles WHERE slot=p_slot::int;
INSERT INTO save_monster_projectiles (slot,map_id,projectile_id,owner_thing_id,projectile_type,x,y,z,vx,vy,vz,sector_id,state,age,damage,impact_player)
SELECT p_slot::int,map_id,projectile_id,owner_thing_id,projectile_type,x,y,z,vx,vy,vz,sector_id,state,age,damage,impact_player FROM monster_projectiles WHERE map_id=p_map_id::int;

DELETE FROM save_world_effects WHERE slot=p_slot::int;
INSERT INTO save_world_effects (slot,map_id,effect_id,effect_type,x,y,z,sector_id,age)
SELECT p_slot::int,map_id,effect_id,effect_type,x,y,z,sector_id,age FROM world_effects WHERE map_id=p_map_id::int;

DELETE FROM save_sectors WHERE slot=p_slot::int;
INSERT INTO save_sectors (slot,id,map_id,floor_height,ceil_height,spawn_floor_height,spawn_ceil_height,spawn_floor_tex,spawn_light_level,floor_tex,ceil_tex,light_level,special,tag)
SELECT p_slot::int,id,map_id,floor_height,ceil_height,spawn_floor_height,spawn_ceil_height,spawn_floor_tex,spawn_light_level,floor_tex,ceil_tex,light_level,special,tag FROM sectors WHERE map_id=p_map_id::int;

DELETE FROM save_sidedefs WHERE slot=p_slot::int;
INSERT INTO save_sidedefs (slot,id,map_id,x_offset,y_offset,upper_tex,lower_tex,mid_tex,sector_id)
SELECT p_slot::int,id,map_id,x_offset,y_offset,upper_tex,lower_tex,mid_tex,sector_id FROM sidedefs WHERE map_id=p_map_id::int;

DELETE FROM save_sector_movers WHERE slot=p_slot::int;
INSERT INTO save_sector_movers (slot,map_id,sector_id,source_line_id,mover_type,plane,direction,bottom_height,top_height,speed,move_carry,wait_tics,countdown,next_ceiling,next_floor,target_floor_tex,moved_this_tick,crush)
SELECT p_slot::int,map_id,sector_id,source_line_id,mover_type,plane,direction,bottom_height,top_height,speed,move_carry,wait_tics,countdown,next_ceiling,next_floor,target_floor_tex,moved_this_tick,crush FROM sector_movers WHERE map_id=p_map_id::int;

DELETE FROM save_line_buttons WHERE slot=p_slot::int;
INSERT INTO save_line_buttons (slot,map_id,line_id,sidedef_id,texture_part,original_tex,active_tex,countdown,just_restored)
SELECT p_slot::int,map_id,line_id,sidedef_id,texture_part,original_tex,active_tex,countdown,just_restored FROM line_buttons WHERE map_id=p_map_id::int;

DELETE FROM save_line_activations WHERE slot=p_slot::int;
INSERT INTO save_line_activations (slot,map_id,line_id)
SELECT p_slot::int,map_id,line_id FROM line_activations WHERE map_id=p_map_id::int;

DELETE FROM save_picked_up_items WHERE slot=p_slot::int;
INSERT INTO save_picked_up_items (slot,map_id,thing_id)
SELECT p_slot::int,map_id,thing_id FROM picked_up_items WHERE map_id=p_map_id::int;

DELETE FROM save_level_secret_discoveries WHERE slot=p_slot::int;
INSERT INTO save_level_secret_discoveries (slot,map_id,player_thing_id,sector_id)
SELECT p_slot::int,map_id,player_thing_id,sector_id FROM level_secret_discoveries WHERE map_id=p_map_id::int;

DELETE FROM save_level_stats WHERE slot=p_slot::int;
INSERT INTO save_level_stats (slot,map_id,player_thing_id,skill_bit,level_tics,par_tics,kills,total_kills,items,total_items,secrets,total_secrets,completed,secret_exit)
SELECT p_slot::int,map_id,player_thing_id,skill_bit,level_tics,par_tics,kills,total_kills,items,total_items,secrets,total_secrets,completed,secret_exit FROM level_stats WHERE map_id=p_map_id::int;

return p_slot::int;
$doom$;

CREATE OR REPLACE FUNCTION doom_load_game(p_slot integer) RETURNS integer
LANGUAGE cedarscript AS $doom$
-- Returns the restored map_id, or -1 when the slot is empty.
let mut target = -1;
SELECT COALESCE(MIN(map_id),-1) AS m FROM save_slots WHERE slot=p_slot::int
{ target = m; }
if target >= 0 {
  DELETE FROM player_state WHERE map_id=target;
  INSERT INTO player_state (map_id,player_thing_id,health,alive,level_tics,previous_x,previous_y,position_x,position_y,base_z,view_z,view_angle,momentum_x,momentum_y,bob_strength,previous_view_z,previous_view_angle,sector_id,pain_face_tics,armor,armor_class,backpack,ammo_bullets,ammo_shells,ammo_rockets,ammo_cells,key_blue,key_yellow,key_red,radsuit_tics,invis_tics,momentum_z,damage_count,bonus_count,light_amp_tics,power_map,god_mode,noclip,invuln_tics,berserk,message,message_tics,frags,death_tics,killer_id,sprite_frame)
  SELECT map_id,player_thing_id,health,alive,level_tics,previous_x,previous_y,position_x,position_y,base_z,view_z,view_angle,momentum_x,momentum_y,bob_strength,previous_view_z,previous_view_angle,sector_id,pain_face_tics,armor,armor_class,backpack,ammo_bullets,ammo_shells,ammo_rockets,ammo_cells,key_blue,key_yellow,key_red,radsuit_tics,invis_tics,momentum_z,damage_count,bonus_count,light_amp_tics,power_map,god_mode,noclip,invuln_tics,berserk,message,message_tics,frags,death_tics,killer_id,sprite_frame FROM save_player_state WHERE slot=p_slot::int;
  DELETE FROM player_weapons WHERE map_id=target;
  INSERT INTO player_weapons (map_id,player_thing_id,current_weapon,pending_weapon,state,seq_index,tics,flash_seq_index,flash_tics,sx,sy,shot_serial,fired_this_tick)
  SELECT map_id,player_thing_id,current_weapon,pending_weapon,state,seq_index,tics,flash_seq_index,flash_tics,sx,sy,shot_serial,fired_this_tick FROM save_player_weapons WHERE slot=p_slot::int;
  DELETE FROM player_weapon_owned WHERE map_id=target;
  INSERT INTO player_weapon_owned (map_id,player_thing_id,weapon_id)
  SELECT map_id,player_thing_id,weapon_id FROM save_player_weapon_owned WHERE slot=p_slot::int;
  DELETE FROM things WHERE map_id=target;
  INSERT INTO things (id,map_id,x,y,z,angle,spawn_x,spawn_y,spawn_angle,mom_x,mom_y,type,flags)
  SELECT id,map_id,x,y,z,angle,spawn_x,spawn_y,spawn_angle,mom_x,mom_y,type,flags FROM save_things WHERE slot=p_slot::int;
  DELETE FROM thing_health WHERE map_id=target;
  INSERT INTO thing_health (map_id,thing_id,health,max_health,alive)
  SELECT map_id,thing_id,health,max_health,alive FROM save_thing_health WHERE slot=p_slot::int;
  DELETE FROM monster_ai WHERE map_id=target;
  INSERT INTO monster_ai (map_id,thing_id,state,state_tics,seq_index,sector_id,attack_cooldown,fired_this_tick,target_thing_id,charge_tics,movedir,movecount)
  SELECT map_id,thing_id,state,state_tics,seq_index,sector_id,attack_cooldown,fired_this_tick,target_thing_id,charge_tics,movedir,movecount FROM save_monster_ai WHERE slot=p_slot::int;
  DELETE FROM monster_projectiles WHERE map_id=target;
  INSERT INTO monster_projectiles (map_id,projectile_id,owner_thing_id,projectile_type,x,y,z,vx,vy,vz,sector_id,state,age,damage,impact_player)
  SELECT map_id,projectile_id,owner_thing_id,projectile_type,x,y,z,vx,vy,vz,sector_id,state,age,damage,impact_player FROM save_monster_projectiles WHERE slot=p_slot::int;
  DELETE FROM world_effects WHERE map_id=target;
  INSERT INTO world_effects (map_id,effect_id,effect_type,x,y,z,sector_id,age)
  SELECT map_id,effect_id,effect_type,x,y,z,sector_id,age FROM save_world_effects WHERE slot=p_slot::int;
  -- The one place this function cannot keep its delete/insert pairs together:
  -- sidedefs reference sectors, so the children go first and come back last.
  DELETE FROM sidedefs WHERE map_id=target;
  DELETE FROM sectors WHERE map_id=target;
  INSERT INTO sectors (id,map_id,floor_height,ceil_height,spawn_floor_height,spawn_ceil_height,spawn_floor_tex,spawn_light_level,floor_tex,ceil_tex,light_level,special,tag)
  SELECT id,map_id,floor_height,ceil_height,spawn_floor_height,spawn_ceil_height,spawn_floor_tex,spawn_light_level,floor_tex,ceil_tex,light_level,special,tag FROM save_sectors WHERE slot=p_slot::int;
  INSERT INTO sidedefs (id,map_id,x_offset,y_offset,upper_tex,lower_tex,mid_tex,sector_id)
  SELECT id,map_id,x_offset,y_offset,upper_tex,lower_tex,mid_tex,sector_id FROM save_sidedefs WHERE slot=p_slot::int;
  DELETE FROM sector_movers WHERE map_id=target;
  INSERT INTO sector_movers (map_id,sector_id,source_line_id,mover_type,plane,direction,bottom_height,top_height,speed,move_carry,wait_tics,countdown,next_ceiling,next_floor,target_floor_tex,moved_this_tick,crush)
  SELECT map_id,sector_id,source_line_id,mover_type,plane,direction,bottom_height,top_height,speed,move_carry,wait_tics,countdown,next_ceiling,next_floor,target_floor_tex,moved_this_tick,crush FROM save_sector_movers WHERE slot=p_slot::int;
  DELETE FROM line_buttons WHERE map_id=target;
  INSERT INTO line_buttons (map_id,line_id,sidedef_id,texture_part,original_tex,active_tex,countdown,just_restored)
  SELECT map_id,line_id,sidedef_id,texture_part,original_tex,active_tex,countdown,just_restored FROM save_line_buttons WHERE slot=p_slot::int;
  DELETE FROM line_activations WHERE map_id=target;
  INSERT INTO line_activations (map_id,line_id)
  SELECT map_id,line_id FROM save_line_activations WHERE slot=p_slot::int;
  DELETE FROM picked_up_items WHERE map_id=target;
  INSERT INTO picked_up_items (map_id,thing_id)
  SELECT map_id,thing_id FROM save_picked_up_items WHERE slot=p_slot::int;
  DELETE FROM level_secret_discoveries WHERE map_id=target;
  INSERT INTO level_secret_discoveries (map_id,player_thing_id,sector_id)
  SELECT map_id,player_thing_id,sector_id FROM save_level_secret_discoveries WHERE slot=p_slot::int;
  DELETE FROM level_stats WHERE map_id=target;
  INSERT INTO level_stats (map_id,player_thing_id,skill_bit,level_tics,par_tics,kills,total_kills,items,total_items,secrets,total_secrets,completed,secret_exit)
  SELECT map_id,player_thing_id,skill_bit,level_tics,par_tics,kills,total_kills,items,total_items,secrets,total_secrets,completed,secret_exit FROM save_level_stats WHERE slot=p_slot::int;
  -- Nothing half-finished from the old session may survive:
  -- these are rebuilt every tic and a stale row would fire.
  DELETE FROM game_tic_commands WHERE map_id=target;
  DELETE FROM line_special_events WHERE map_id=target;
  DELETE FROM line_use_results WHERE map_id=target;
  DELETE FROM pickup_touches WHERE map_id=target;
  DELETE FROM pickup_grants WHERE map_id=target;
  DELETE FROM sound_events WHERE map_id=target;
  DELETE FROM hitscan_hits WHERE map_id=target;
  DELETE FROM projectile_damage WHERE map_id=target;
  DELETE FROM projectile_impacts WHERE map_id=target;
  DELETE FROM monster_attack_damage WHERE map_id=target;
  -- Derived mirrors, rebuilt from the state just restored.
  doom_materialize_render_segs(target);
  doom_materialize_render_things(target);
  DELETE FROM sector_light_fx WHERE map_id=target;
  INSERT INTO sector_light_fx
    (map_id, sector_id, special, base_light, dark_light)
  SELECT s.map_id, s.id, s.special::smallint,
         COALESCE(s.spawn_light_level, s.light_level)::smallint,
         LEAST(COALESCE(s.spawn_light_level, s.light_level),
               COALESCE(MIN(other.light_level), 0::smallint))::smallint
  FROM sectors s
  LEFT JOIN linedefs edge ON edge.map_id = s.map_id
  LEFT JOIN sidedefs r ON r.map_id = edge.map_id AND r.id = edge.right_sd_id
  LEFT JOIN sidedefs l ON l.map_id = edge.map_id AND l.id = edge.left_sd_id
  LEFT JOIN sectors other ON other.map_id = s.map_id
    AND other.id = CASE WHEN r.sector_id = s.id THEN l.sector_id
                        WHEN l.sector_id = s.id THEN r.sector_id END
  WHERE s.map_id = target AND s.special IN (1,2,3,8,12,13,17)
  GROUP BY s.map_id, s.id, s.special, s.spawn_light_level, s.light_level;
}
return target;
$doom$;
