-- Static Doom gameplay catalogs derived from the original info.c tables.

-- These tables are refreshed atomically with the WAD sprite assets.

TRUNCATE thing_combat_defs;
TRUNCATE thing_ai_frames;
TRUNCATE pickup_defs;
TRUNCATE weapon_frames;
DELETE FROM weapon_defs;
DELETE FROM thing_sprite_defs;
DELETE FROM projectile_defs;
TRUNCATE effect_sprite_defs;
TRUNCATE thing_blocking_defs;
TRUNCATE thing_role_defs;
TRUNCATE sector_special_defs;
TRUNCATE ammo_defs;
TRUNCATE chase_dir_defs;
TRUNCATE level_pars;
TRUNCATE boss_actions;
TRUNCATE finale_defs;
TRUNCATE line_special_defs;
TRUNCATE thing_sound_defs;
TRUNCATE pickup_messages;

INSERT INTO thing_sprite_defs (thing_type,sprite,frame,fullbright,spawn_ceiling,thing_height) VALUES
  (3004,'POSS','A',FALSE,FALSE,56),
  (9,'SPOS','A',FALSE,FALSE,56),
  (64,'VILE','A',FALSE,FALSE,56),
  (66,'SKEL','A',FALSE,FALSE,56),
  (67,'FATT','A',FALSE,FALSE,64),
  (65,'CPOS','A',FALSE,FALSE,56),
  (3001,'TROO','A',FALSE,FALSE,56),
  (3002,'SARG','A',FALSE,FALSE,56),
  (58,'SARG','A',FALSE,FALSE,56),
  (3005,'HEAD','A',FALSE,FALSE,56),
  (3003,'BOSS','A',FALSE,FALSE,64),
  (69,'BOS2','A',FALSE,FALSE,64),
  (3006,'SKUL','A',TRUE,FALSE,56),
  (7,'SPID','A',FALSE,FALSE,100),
  (68,'BSPI','A',FALSE,FALSE,64),
  (16,'CYBR','A',FALSE,FALSE,110),
  (71,'PAIN','A',FALSE,FALSE,56),
  (84,'SSWV','A',FALSE,FALSE,56),
  (72,'KEEN','A',FALSE,TRUE,72),
  (88,'BBRN','A',FALSE,FALSE,16),
  (89,'SSWV','A',FALSE,FALSE,32),
  (2035,'BAR1','A',FALSE,FALSE,42),
  (2018,'ARM1','A',FALSE,FALSE,16),
  (2019,'ARM2','A',FALSE,FALSE,16),
  (2014,'BON1','A',FALSE,FALSE,16),
  (2015,'BON2','A',FALSE,FALSE,16),
  (5,'BKEY','A',FALSE,FALSE,16),
  (13,'RKEY','A',FALSE,FALSE,16),
  (6,'YKEY','A',FALSE,FALSE,16),
  (39,'YSKU','A',FALSE,FALSE,16),
  (38,'RSKU','A',FALSE,FALSE,16),
  (40,'BSKU','A',FALSE,FALSE,16),
  (2011,'STIM','A',FALSE,FALSE,16),
  (2012,'MEDI','A',FALSE,FALSE,16),
  (2013,'SOUL','A',TRUE,FALSE,16),
  (2022,'PINV','A',TRUE,FALSE,16),
  (2023,'PSTR','A',TRUE,FALSE,16),
  (2024,'PINS','A',TRUE,FALSE,16),
  (2025,'SUIT','A',TRUE,FALSE,16),
  (2026,'PMAP','A',TRUE,FALSE,16),
  (2045,'PVIS','A',TRUE,FALSE,16),
  (83,'MEGA','A',TRUE,FALSE,16),
  (2007,'CLIP','A',FALSE,FALSE,16),
  (2048,'AMMO','A',FALSE,FALSE,16),
  (2010,'ROCK','A',FALSE,FALSE,16),
  (2046,'BROK','A',FALSE,FALSE,16),
  (2047,'CELL','A',FALSE,FALSE,16),
  (17,'CELP','A',FALSE,FALSE,16),
  (2008,'SHEL','A',FALSE,FALSE,16),
  (2049,'SBOX','A',FALSE,FALSE,16),
  (8,'BPAK','A',FALSE,FALSE,16),
  (2006,'BFUG','A',FALSE,FALSE,16),
  (2002,'MGUN','A',FALSE,FALSE,16),
  (2005,'CSAW','A',FALSE,FALSE,16),
  (2003,'LAUN','A',FALSE,FALSE,16),
  (2004,'PLAS','A',FALSE,FALSE,16),
  (2001,'SHOT','A',FALSE,FALSE,16),
  (82,'SGN2','A',FALSE,FALSE,16),
  (85,'TLMP','A',TRUE,FALSE,16),
  (86,'TLP2','A',TRUE,FALSE,16),
  (2028,'COLU','A',TRUE,FALSE,16),
  (30,'COL1','A',FALSE,FALSE,16),
  (31,'COL2','A',FALSE,FALSE,16),
  (32,'COL3','A',FALSE,FALSE,16),
  (33,'COL4','A',FALSE,FALSE,16),
  (37,'COL6','A',FALSE,FALSE,16),
  (36,'COL5','A',FALSE,FALSE,16),
  (41,'CEYE','A',TRUE,FALSE,16),
  (42,'FSKU','A',TRUE,FALSE,16),
  (43,'TRE1','A',FALSE,FALSE,16),
  (44,'TBLU','A',TRUE,FALSE,16),
  (45,'TGRN','A',TRUE,FALSE,16),
  (46,'TRED','A',TRUE,FALSE,16),
  (55,'SMBT','A',TRUE,FALSE,16),
  (56,'SMGT','A',TRUE,FALSE,16),
  (57,'SMRT','A',TRUE,FALSE,16),
  (47,'SMIT','A',FALSE,FALSE,16),
  (48,'ELEC','A',FALSE,FALSE,16),
  (34,'CAND','A',TRUE,FALSE,16),
  (35,'CBRA','A',TRUE,FALSE,16),
  (49,'GOR1','A',FALSE,TRUE,68),
  (50,'GOR2','A',FALSE,TRUE,84),
  (51,'GOR3','A',FALSE,TRUE,84),
  (52,'GOR4','A',FALSE,TRUE,68),
  (53,'GOR5','A',FALSE,TRUE,52),
  (59,'GOR2','A',FALSE,TRUE,84),
  (60,'GOR4','A',FALSE,TRUE,68),
  (61,'GOR3','A',FALSE,TRUE,52),
  (62,'GOR5','A',FALSE,TRUE,52),
  (63,'GOR1','A',FALSE,TRUE,68),
  (22,'HEAD','L',FALSE,FALSE,16),
  (15,'PLAY','N',FALSE,FALSE,16),
  (18,'POSS','L',FALSE,FALSE,16),
  (21,'SARG','N',FALSE,FALSE,16),
  (23,'SKUL','K',FALSE,FALSE,16),
  (20,'TROO','M',FALSE,FALSE,16),
  (19,'SPOS','L',FALSE,FALSE,16),
  (10,'PLAY','W',FALSE,FALSE,16),
  (12,'PLAY','W',FALSE,FALSE,16),
  (28,'POL2','A',FALSE,FALSE,16),
  (24,'POL5','A',FALSE,FALSE,16),
  (27,'POL4','A',FALSE,FALSE,16),
  (29,'POL3','A',TRUE,FALSE,16),
  (25,'POL1','A',FALSE,FALSE,16),
  (26,'POL6','A',FALSE,FALSE,16),
  (54,'TRE2','A',FALSE,FALSE,16),
  (70,'FCAN','A',TRUE,FALSE,16),
  (73,'HDB1','A',FALSE,TRUE,88),
  (74,'HDB2','A',FALSE,TRUE,88),
  (75,'HDB3','A',FALSE,TRUE,64),
  (76,'HDB4','A',FALSE,TRUE,64),
  (77,'HDB5','A',FALSE,TRUE,64),
  (78,'HDB6','A',FALSE,TRUE,64),
  (79,'POB1','A',FALSE,FALSE,16),
  (80,'POB2','A',FALSE,FALSE,16),
  (81,'BRS1','A',FALSE,FALSE,16);

INSERT INTO projectile_defs
  (projectile_type,name,radius,speed,dmg_dice_mult,dmg_random_id,
   explode_tics,fly_timeout,blast_radius,spray_at_tic,
   spray_rays,spray_arc_degrees,spray_range,spray_dice,spray_random_base,
   fly_sprite,impact_sprite,dmg_dice_count) VALUES
  ('rocket','rocket',        11.0,20.0, 20, 8,18,700,128.0,NULL,NULL,NULL,NULL,NULL,NULL,'MISL','MISL',8),
  ('plasma','plasma ball',   13.0,25.0,  5, 9,20,700, NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PLSS','PLSE',8),
  ('bfg','BFG ball',         13.0,25.0,100,10,48,700, NULL,  16,  40,90.0,1024.0,  15,  20,'BFS1','BFE1',8),
  ('imp_fireball','imp fireball',       6.0,NULL,NULL,NULL,15,700,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'BAL1','BAL1',8),
  ('caco_fireball','cacodemon fireball',6.0,NULL,NULL,NULL,15,700,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'BAL2','BAL2',8),
  ('baron_fireball','baron fireball',   6.0,NULL,NULL,NULL,15,700,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'BAL7','BAL7',8);

INSERT INTO thing_combat_defs (thing_type,spawn_health,radius,death_sprite,death_frame,death_fullbright,no_blood,pain_chance,attack_range,xdeath_frame,mass,counts_kill,
  name,height,floats,skull_fly,missile_type,missile_speed,missile_dice,hitscan_pellets,melee_mult,melee_sides,fast_on_nightmare,attack_sound,explodes,
  hitscan_mult,hitscan_sides,charge_mult,charge_sides,blast_radius,fuzzy,drops_thing_type) VALUES
  (3004,20,20,'POSS','L',FALSE,FALSE,200,2048, 'U',  100,TRUE, 'zombieman',56,FALSE,FALSE,NULL,NULL,NULL,1,NULL,NULL,FALSE,'DSPISTOL',FALSE,3,5,NULL,NULL,NULL,FALSE,2007),
  (9,30,20,'SPOS','L',FALSE,FALSE,170,2048, 'U',  100,TRUE, 'shotgun guy',56,FALSE,FALSE,NULL,NULL,NULL,3,NULL,NULL,FALSE,'DSSHOTGN',FALSE,3,5,NULL,NULL,NULL,FALSE,2001),
  (64,700,20,'VILE','Z',FALSE,FALSE,0,2048,NULL,  500,FALSE, 'arch-vile',56,FALSE,FALSE,NULL,NULL,NULL,NULL,NULL,NULL,FALSE,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,FALSE,NULL),
  (66,300,20,'SKEL','Q',FALSE,FALSE,0,2048,NULL,  500,FALSE, 'revenant',56,FALSE,FALSE,NULL,NULL,NULL,NULL,NULL,NULL,FALSE,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,FALSE,NULL),
  (67,600,48,'FATT','T',FALSE,FALSE,0,2048,NULL, 1000,FALSE, 'mancubus',64,FALSE,FALSE,NULL,NULL,NULL,NULL,NULL,NULL,FALSE,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,FALSE,NULL),
  (65,70,20,'CPOS','N',FALSE,FALSE,0,2048,NULL,  100,FALSE, 'chaingunner',56,FALSE,FALSE,NULL,NULL,NULL,NULL,NULL,NULL,FALSE,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,FALSE,NULL),
  (3001,60,20,'TROO','M',FALSE,FALSE,200,2048, 'U',  100,TRUE, 'imp',56,FALSE,FALSE,'imp_fireball',10,3,NULL,3,8,FALSE,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,FALSE,NULL),
  (3002,150,30,'SARG','N',FALSE,FALSE,180,  68,NULL,  400,TRUE, 'demon',56,FALSE,FALSE,NULL,NULL,NULL,NULL,4,10,TRUE,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,FALSE,NULL),
  (58,150,30,'SARG','N',FALSE,FALSE,180,  68,NULL,  400,TRUE, 'spectre',56,FALSE,FALSE,NULL,NULL,NULL,NULL,4,10,TRUE,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,TRUE,NULL),
  (3005,400,31,'HEAD','L',FALSE,FALSE,128,2048,NULL,  400,FALSE, 'cacodemon',56,TRUE,FALSE,'caco_fireball',10,5,NULL,10,6,FALSE,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,FALSE,NULL),
  (3003,1000,24,'BOSS','O',FALSE,FALSE,50,2048,NULL, 1000,TRUE, 'baron of hell',64,FALSE,FALSE,'baron_fireball',15,8,NULL,10,8,FALSE,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,FALSE,NULL),
  (69,500,24,'BOS2','O',FALSE,FALSE,0,2048,NULL, 1000,FALSE, 'hell knight',64,FALSE,FALSE,NULL,NULL,NULL,NULL,NULL,NULL,FALSE,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,FALSE,NULL),
  (3006,100,16,'SKUL','K',FALSE,FALSE,256,2048,NULL,   50,FALSE, 'lost soul',56,TRUE,TRUE,NULL,NULL,NULL,NULL,NULL,NULL,FALSE,NULL,FALSE,NULL,NULL,3,8,NULL,FALSE,NULL),
  (7,3000,128,'SPID','S',FALSE,FALSE,40,2048,NULL, 1000,FALSE, 'spider mastermind',100,FALSE,FALSE,NULL,NULL,NULL,3,NULL,NULL,FALSE,'DSSHOTGN',FALSE,3,5,NULL,NULL,NULL,FALSE,NULL),
  (68,500,64,'BSPI','P',FALSE,FALSE,0,2048,NULL,  600,FALSE, 'arachnotron',64,FALSE,FALSE,NULL,NULL,NULL,NULL,NULL,NULL,FALSE,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,FALSE,NULL),
  (16,4000,40,'CYBR','P',FALSE,FALSE,20,2048,NULL, 1000,FALSE, 'cyberdemon',110,FALSE,FALSE,'rocket',20,20,NULL,NULL,NULL,FALSE,'DSRLAUNC',FALSE,NULL,NULL,NULL,NULL,NULL,FALSE,NULL),
  (71,400,31,'PAIN','M',TRUE,FALSE,0,2048,NULL,  400,FALSE, 'pain elemental',56,TRUE,FALSE,NULL,NULL,NULL,NULL,NULL,NULL,FALSE,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,FALSE,NULL),
  (84,50,20,'SSWV','M',FALSE,FALSE,0,2048,NULL,  100,FALSE, 'wolfenstein ss',56,FALSE,FALSE,NULL,NULL,NULL,NULL,NULL,NULL,FALSE,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,FALSE,NULL),
  (72,100,16,'KEEN','L',FALSE,FALSE,0,2048,NULL,  100,FALSE, 'commander keen',72,FALSE,FALSE,NULL,NULL,NULL,NULL,NULL,NULL,FALSE,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,FALSE,NULL),
  (88,250,16,'BBRN','A',FALSE,TRUE,0,2048,NULL,10000,FALSE, 'romero''s head',16,FALSE,FALSE,NULL,NULL,NULL,NULL,NULL,NULL,FALSE,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,FALSE,NULL),
  (2035,20,10,'BEXP','E',TRUE,TRUE,0,   0,NULL,  100,FALSE, 'barrel',42,FALSE,FALSE,NULL,NULL,NULL,NULL,NULL,NULL,FALSE,'DSBAREXP',TRUE,NULL,NULL,NULL,NULL,128,FALSE,NULL);

-- P_NewChaseDir's eight compass directions (dirtype_t).
INSERT INTO chase_dir_defs (dir,name,dx,dy,angle,opposite,is_diagonal) VALUES
  (0,'east',       1.00000, 0.00000,   0, 4, FALSE),
  (1,'north-east', 0.71716, 0.71716,  45, 5, TRUE ),
  (2,'north',      0.00000, 1.00000,  90, 6, FALSE),
  (3,'north-west',-0.71716, 0.71716, 135, 7, TRUE ),
  (4,'west',      -1.00000, 0.00000, 180, 0, FALSE),
  (5,'south-west',-0.71716,-0.71716, 225, 1, TRUE ),
  (6,'south',      0.00000,-1.00000, 270, 2, FALSE),
  (7,'south-east', 0.71716,-0.71716, 315, 3, TRUE );

INSERT INTO effect_sprite_defs
  (effect_type,sprite,frame_sequence,tics_per_frame,fullbright) VALUES
  ('puff','PUFF','ABCD',4,TRUE),
  -- S_BLOOD runs backwards through its letters.
  ('blood','BLUD','CBA',8,FALSE),
  -- S_TFOG runs A B A B C D E F G H I J.
  ('tfog','TFOG','ABABCDEFGHIJ',6,TRUE),
  ('ifog','IFOG','ABCDE',6,TRUE),
  ('bfg_spray','BFE2','ABCD',8,TRUE);

INSERT INTO ammo_defs (ammo_type,cap,backpack_cap,backpack_gives) VALUES
  ('bullets',200,400,10),
  ('shells',  50,100, 4),
  ('rockets', 50,100, 1),
  ('cells',  300,600,20);

INSERT INTO sector_special_defs (special,name,is_secret,damage_per_hit,ends_level_at_low_health,exit_at_health) VALUES
  ( 1,'light blink random',       FALSE,NULL,FALSE,NULL),
  ( 2,'light blink 0.5 s',        FALSE,NULL,FALSE,NULL),
  ( 3,'light blink 1 s',          FALSE,NULL,FALSE,NULL),
  ( 4,'damage 20% and blink',     FALSE,20,FALSE,NULL),
  ( 5,'damage 10%',               FALSE,10,FALSE,NULL),
  ( 7,'damage 5% nukage',         FALSE,5,FALSE,NULL),
  ( 8,'light glow',               FALSE,NULL,FALSE,NULL),
  ( 9,'secret',                    TRUE,NULL,FALSE,NULL),
  (10,'door closes after 30 s',   FALSE,NULL,FALSE,NULL),
  (11,'damage 20% and end level', FALSE,20,TRUE,10),
  (12,'light blink 0.5 s sync',   FALSE,NULL,FALSE,NULL),
  (13,'light blink 1 s sync',     FALSE,NULL,FALSE,NULL),
  (14,'door opens after 300 s',   FALSE,NULL,FALSE,NULL),
  (16,'damage 20%',               FALSE,20,FALSE,NULL),
  (17,'light flicker',            FALSE,NULL,FALSE,NULL);

-- The Things that are a place
INSERT INTO thing_role_defs
  (thing_type,name,is_player_start,player_number,is_deathmatch_start,is_teleport_dest) VALUES
  ( 1,'player 1 start',   TRUE, 1,FALSE,FALSE),
  ( 2,'player 2 start',   TRUE, 2,FALSE,FALSE),
  ( 3,'player 3 start',   TRUE, 3,FALSE,FALSE),
  ( 4,'player 4 start',   TRUE, 4,FALSE,FALSE),
  (11,'deathmatch start',FALSE,NULL, TRUE,FALSE),
  (14,'teleport destination',FALSE,NULL,FALSE,TRUE);

INSERT INTO thing_blocking_defs (thing_type,radius) VALUES
  (  35,16),   -- Candelabra
  (  46,16),   -- Tall red firestick
  (  48,16),   -- Tall techno pillar
  (2028,16);   -- Floor lamp


INSERT INTO thing_ai_frames (thing_type,state,seq_index,frame,tics,fullbright,is_attack_frame) VALUES
  (3004,'see',0,'A',8,FALSE,FALSE),
  (3004,'see',1,'B',8,FALSE,FALSE),
  (3004,'see',2,'C',8,FALSE,FALSE),
  (3004,'see',3,'D',8,FALSE,FALSE),
  (3004,'missile',0,'E',10,FALSE,FALSE),
  (3004,'missile',1,'F',8,TRUE,TRUE),
  (3004,'pain',0,'G',6,FALSE,FALSE),
  (3004,'die',0,'H',5,FALSE,FALSE),
  (3004,'die',1,'I',5,FALSE,FALSE),
  (3004,'die',2,'J',5,FALSE,FALSE),
  (3004,'die',3,'K',5,FALSE,FALSE),
  (9,'see',0,'A',6,FALSE,FALSE),
  (9,'see',1,'B',6,FALSE,FALSE),
  (9,'see',2,'C',6,FALSE,FALSE),
  (9,'see',3,'D',6,FALSE,FALSE),
  (9,'missile',0,'E',10,FALSE,FALSE),
  (9,'missile',1,'F',8,TRUE,TRUE),
  (9,'pain',0,'G',6,FALSE,FALSE),
  (9,'die',0,'H',5,FALSE,FALSE),
  (9,'die',1,'I',5,FALSE,FALSE),
  (9,'die',2,'J',5,FALSE,FALSE),
  (9,'die',3,'K',5,FALSE,FALSE),
  (3001,'see',0,'A',6,FALSE,FALSE),
  (3001,'see',1,'B',6,FALSE,FALSE),
  (3001,'see',2,'C',6,FALSE,FALSE),
  (3001,'see',3,'D',6,FALSE,FALSE),
  (3001,'missile',0,'E',8,FALSE,FALSE),
  (3001,'missile',1,'F',8,FALSE,FALSE),
  (3001,'missile',2,'G',6,FALSE,TRUE),
  (3001,'pain',0,'H',4,FALSE,FALSE),
  (3001,'die',0,'I',5,FALSE,FALSE),
  (3001,'die',1,'J',5,FALSE,FALSE),
  (3001,'die',2,'K',5,FALSE,FALSE),
  (3001,'die',3,'L',5,FALSE,FALSE),
  (3002,'see',0,'A',4,FALSE,FALSE),
  (3002,'see',1,'B',4,FALSE,FALSE),
  (3002,'see',2,'C',4,FALSE,FALSE),
  (3002,'see',3,'D',4,FALSE,FALSE),
  (3002,'missile',0,'E',8,FALSE,FALSE),
  (3002,'missile',1,'F',8,FALSE,FALSE),
  (3002,'missile',2,'G',8,FALSE,TRUE),
  (3002,'pain',0,'H',4,FALSE,FALSE),
  (3002,'die',0,'I',8,FALSE,FALSE),
  (3002,'die',1,'J',8,FALSE,FALSE),
  (3002,'die',2,'K',4,FALSE,FALSE),
  (3002,'die',3,'L',4,FALSE,FALSE),
  (3002,'die',4,'M',4,FALSE,FALSE),
  (58,'see',0,'A',4,FALSE,FALSE),
  (58,'see',1,'B',4,FALSE,FALSE),
  (58,'see',2,'C',4,FALSE,FALSE),
  (58,'see',3,'D',4,FALSE,FALSE),
  (58,'missile',0,'E',8,FALSE,FALSE),
  (58,'missile',1,'F',8,FALSE,FALSE),
  (58,'missile',2,'G',8,FALSE,TRUE),
  (58,'pain',0,'H',4,FALSE,FALSE),
  (58,'die',0,'I',8,FALSE,FALSE),
  (58,'die',1,'J',8,FALSE,FALSE),
  (58,'die',2,'K',4,FALSE,FALSE),
  (58,'die',3,'L',4,FALSE,FALSE),
  (58,'die',4,'M',4,FALSE,FALSE),
  (3003,'see',0,'A',6,FALSE,FALSE),
  (3003,'see',1,'B',6,FALSE,FALSE),
  (3003,'see',2,'C',6,FALSE,FALSE),
  (3003,'see',3,'D',6,FALSE,FALSE),
  (3003,'missile',0,'E',8,FALSE,FALSE),
  (3003,'missile',1,'F',8,FALSE,FALSE),
  (3003,'missile',2,'G',8,FALSE,TRUE),
  (3003,'pain',0,'H',4,FALSE,FALSE),
  (3003,'die',0,'I',8,FALSE,FALSE),
  (3003,'die',1,'J',8,FALSE,FALSE),
  (3003,'die',2,'K',8,FALSE,FALSE),
  (3003,'die',3,'L',8,FALSE,FALSE),
  (3003,'die',4,'M',8,FALSE,FALSE),
  (3003,'die',5,'N',8,FALSE,FALSE),
  (2035,'die',0,'A',5,TRUE,FALSE),
  (2035,'die',1,'B',5,TRUE,FALSE),
  (2035,'die',2,'C',5,TRUE,TRUE),
  (2035,'die',3,'D',10,TRUE,FALSE),
  (2035,'die',4,'E',10,TRUE,FALSE),
  (3004,'xdeath',0,'M',5,FALSE,FALSE),
  (3004,'xdeath',1,'N',5,FALSE,FALSE),
  (3004,'xdeath',2,'O',5,FALSE,FALSE),
  (3004,'xdeath',3,'P',5,FALSE,FALSE),
  (3004,'xdeath',4,'Q',5,FALSE,FALSE),
  (3004,'xdeath',5,'R',5,FALSE,FALSE),
  (3004,'xdeath',6,'S',5,FALSE,FALSE),
  (3004,'xdeath',7,'T',5,FALSE,FALSE),
  (9,'xdeath',0,'M',5,FALSE,FALSE),
  (9,'xdeath',1,'N',5,FALSE,FALSE),
  (9,'xdeath',2,'O',5,FALSE,FALSE),
  (9,'xdeath',3,'P',5,FALSE,FALSE),
  (9,'xdeath',4,'Q',5,FALSE,FALSE),
  (9,'xdeath',5,'R',5,FALSE,FALSE),
  (9,'xdeath',6,'S',5,FALSE,FALSE),
  (9,'xdeath',7,'T',5,FALSE,FALSE),
  (3001,'xdeath',0,'N',5,FALSE,FALSE),
  (3001,'xdeath',1,'O',5,FALSE,FALSE),
  (3001,'xdeath',2,'P',5,FALSE,FALSE),
  (3001,'xdeath',3,'Q',5,FALSE,FALSE),
  (3001,'xdeath',4,'R',5,FALSE,FALSE),
  (3001,'xdeath',5,'S',5,FALSE,FALSE),
  (3001,'xdeath',6,'T',5,FALSE,FALSE),
  (3005,'see',0,'A',3,FALSE,FALSE),
  (3005,'see',1,'A',3,FALSE,FALSE),
  (3005,'see',2,'A',3,FALSE,FALSE),
  (3005,'see',3,'A',3,FALSE,FALSE),
  (3005,'missile',0,'B',5,FALSE,FALSE),
  (3005,'missile',1,'C',5,FALSE,FALSE),
  (3005,'missile',2,'D',5,FALSE,TRUE),
  (3005,'pain',0,'E',3,FALSE,FALSE),
  (3005,'pain',1,'E',3,FALSE,FALSE),
  (3005,'die',0,'F',8,FALSE,FALSE),
  (3005,'die',1,'G',8,FALSE,FALSE),
  (3005,'die',2,'H',8,FALSE,FALSE),
  (3005,'die',3,'I',8,FALSE,FALSE),
  (3005,'die',4,'J',8,FALSE,FALSE),
  (3005,'die',5,'K',8,FALSE,FALSE),
  (3006,'see',0,'A',6,TRUE,FALSE),
  (3006,'see',1,'B',6,TRUE,FALSE),
  (3006,'missile',0,'C',10,TRUE,FALSE),
  (3006,'missile',1,'D',4,TRUE,TRUE),
  (3006,'pain',0,'E',3,TRUE,FALSE),
  (3006,'pain',1,'E',3,TRUE,FALSE),
  (3006,'die',0,'F',6,TRUE,FALSE),
  (3006,'die',1,'G',6,TRUE,FALSE),
  (3006,'die',2,'H',6,TRUE,FALSE),
  (3006,'die',3,'I',6,TRUE,FALSE),
  (3006,'die',4,'J',6,TRUE,FALSE),
  (3006,'die',5,'K',6,TRUE,FALSE),
  (16,'see',0,'A',3,FALSE,FALSE),
  (16,'see',1,'B',3,FALSE,FALSE),
  (16,'see',2,'C',3,FALSE,FALSE),
  (16,'see',3,'D',3,FALSE,FALSE),
  (16,'missile',0,'E',6,FALSE,FALSE),
  (16,'missile',1,'F',12,FALSE,TRUE),
  (16,'missile',2,'E',12,FALSE,FALSE),
  (16,'missile',3,'F',12,FALSE,TRUE),
  (16,'missile',4,'E',12,FALSE,FALSE),
  (16,'missile',5,'F',12,FALSE,TRUE),
  (16,'pain',0,'G',10,FALSE,FALSE),
  (16,'die',0,'H',10,FALSE,FALSE),
  (16,'die',1,'I',10,FALSE,FALSE),
  (16,'die',2,'J',10,FALSE,FALSE),
  (16,'die',3,'K',10,FALSE,FALSE),
  (16,'die',4,'L',10,FALSE,FALSE),
  (16,'die',5,'M',10,FALSE,FALSE),
  (16,'die',6,'N',10,FALSE,FALSE),
  (16,'die',7,'O',10,FALSE,FALSE),
  (16,'die',8,'P',30,FALSE,FALSE),
  (7,'see',0,'A',3,FALSE,FALSE),
  (7,'see',1,'B',3,FALSE,FALSE),
  (7,'see',2,'C',3,FALSE,FALSE),
  (7,'see',3,'D',3,FALSE,FALSE),
  (7,'see',4,'E',3,FALSE,FALSE),
  (7,'see',5,'F',3,FALSE,FALSE),
  (7,'missile',0,'A',20,FALSE,FALSE),
  (7,'missile',1,'G',4,FALSE,TRUE),
  (7,'missile',2,'H',4,FALSE,TRUE),
  (7,'missile',3,'H',1,FALSE,FALSE),
  (7,'pain',0,'I',3,FALSE,FALSE),
  (7,'pain',1,'I',3,FALSE,FALSE),
  (7,'die',0,'J',20,FALSE,FALSE),
  (7,'die',1,'K',10,FALSE,FALSE),
  (7,'die',2,'L',10,FALSE,FALSE),
  (7,'die',3,'M',10,FALSE,FALSE),
  (7,'die',4,'N',10,FALSE,FALSE),
  (7,'die',5,'O',10,FALSE,FALSE),
  (7,'die',6,'P',10,FALSE,FALSE),
  (7,'die',7,'Q',10,FALSE,FALSE),
  (7,'die',8,'R',10,FALSE,FALSE),
  (7,'die',9,'S',30,FALSE,FALSE);


INSERT INTO pickup_defs (thing_type,kind,amount,cap,is_set_min,weapon_id,armor_class,counts_item,dropped_amount,only_when_below_cap) VALUES
  (2011,'health',10,100,FALSE,NULL,NULL,FALSE,NULL,TRUE),
  (2012,'health',25,100,FALSE,NULL,NULL,FALSE,NULL,TRUE),
  (2014,'health',1,200,FALSE,NULL,NULL,TRUE,NULL,FALSE),
  (2013,'health',100,200,FALSE,NULL,NULL,TRUE,NULL,FALSE),
  (2023,'health',100,100,TRUE,NULL,NULL,TRUE,NULL,FALSE),
  (2015,'armor',1,200,FALSE,NULL,1,TRUE,NULL,FALSE),
  (2018,'armor',100,100,TRUE,NULL,1,FALSE,NULL,FALSE),
  (2019,'armor',200,200,TRUE,NULL,2,FALSE,NULL,FALSE),
  (2007,'bullets',10,200,FALSE,NULL,NULL,FALSE,5,FALSE),
  (2048,'bullets',50,200,FALSE,NULL,NULL,FALSE,NULL,FALSE),
  (2008,'shells',4,50,FALSE,NULL,NULL,FALSE,NULL,FALSE),
  (2049,'shells',20,50,FALSE,NULL,NULL,FALSE,NULL,FALSE),
  (2010,'rockets',1,50,FALSE,NULL,NULL,FALSE,NULL,FALSE),
  (2046,'rockets',5,50,FALSE,NULL,NULL,FALSE,NULL,FALSE),
  (2047,'cells',20,300,FALSE,NULL,NULL,FALSE,NULL,FALSE),
  (17,'cells',100,300,FALSE,NULL,NULL,FALSE,NULL,FALSE),
  (8,'backpack',1,0,FALSE,NULL,NULL,FALSE,NULL,FALSE),
  (5,'key_blue',1,1,TRUE,NULL,NULL,FALSE,NULL,FALSE),
  (6,'key_yellow',1,1,TRUE,NULL,NULL,FALSE,NULL,FALSE),
  (13,'key_red',1,1,TRUE,NULL,NULL,FALSE,NULL,FALSE),
  (38,'key_red',1,1,TRUE,NULL,NULL,FALSE,NULL,FALSE),
  (39,'key_yellow',1,1,TRUE,NULL,NULL,FALSE,NULL,FALSE),
  (40,'key_blue',1,1,TRUE,NULL,NULL,FALSE,NULL,FALSE),
  (2001,'weapon',0,0,FALSE,3,NULL,FALSE,NULL,FALSE),
  (2001,'shells',8,50,FALSE,NULL,NULL,FALSE,4,FALSE),
  (2002,'weapon',0,0,FALSE,4,NULL,FALSE,NULL,FALSE),
  (2002,'bullets',20,200,FALSE,NULL,NULL,FALSE,NULL,FALSE),
  (2003,'weapon',0,0,FALSE,5,NULL,FALSE,NULL,FALSE),
  (2003,'rockets',2,50,FALSE,NULL,NULL,FALSE,NULL,FALSE),
  (2004,'weapon',0,0,FALSE,6,NULL,FALSE,NULL,FALSE),
  (2004,'cells',40,300,FALSE,NULL,NULL,FALSE,NULL,FALSE),
  (2006,'weapon',0,0,FALSE,7,NULL,FALSE,NULL,FALSE),
  (2006,'cells',40,300,FALSE,NULL,NULL,FALSE,NULL,FALSE),
  (2005,'weapon',0,0,FALSE,8,NULL,FALSE,NULL,FALSE),
  (2025,'radsuit',2100,2100,FALSE,NULL,NULL,TRUE,NULL,FALSE),
  (2022,'invuln',1050,1050,FALSE,NULL,NULL,TRUE,NULL,FALSE),
  (2024,'invis',2100,2100,FALSE,NULL,NULL,TRUE,NULL,FALSE),
  (2026,'powermap',1,1,FALSE,NULL,NULL,TRUE,NULL,FALSE),
  (2045,'lightamp',4200,4200,FALSE,NULL,NULL,TRUE,NULL,FALSE);

INSERT INTO weapon_defs (weapon_id,name,slot,ammo_type,ammo_per_shot,sprite,flash_sprite,pellet_count,max_range,dmg_dice_count,dmg_dice_mult,projectile_type,idle_loop_sound) VALUES
  (1,'fist',1,NULL,0,'PUNG',NULL,1,64.0,10,2,NULL,NULL),
  (2,'pistol',2,'bullets',1,'PISG','PISF',1,2048.0,3,5,NULL,NULL),
  (3,'shotgun',3,'shells',1,'SHTG','SHTF',7,2048.0,3,5,NULL,NULL),
  (4,'chaingun',4,'bullets',1,'CHGG','CHGF',1,2048.0,3,5,NULL,NULL),
  (5,'rocket launcher',5,'rockets',1,'MISG','MISF',0,0.0,0,0,'rocket',NULL),
  (6,'plasma rifle',6,'cells',1,'PLSG','PLSF',0,0.0,0,0,'plasma',NULL),
  (7,'BFG9000',7,'cells',40,'BFGG','BFGF',0,0.0,0,0,'bfg',NULL),
  (8,'chainsaw',1,NULL,0,'SAWG',NULL,1,65.0,10,2,NULL,'DSSAWIDL');

INSERT INTO weapon_frames (weapon_id,state,seq_index,frame,tics,fullbright,is_attack_frame,refire_check) VALUES
  (1,'ready',0,'A',1,FALSE,FALSE,FALSE),
  (1,'fire',0,'B',4,FALSE,FALSE,FALSE),
  (1,'fire',1,'C',4,FALSE,TRUE,FALSE),
  (1,'fire',2,'D',5,FALSE,FALSE,FALSE),
  (1,'fire',3,'D',5,FALSE,FALSE,TRUE),
  (2,'ready',0,'A',1,FALSE,FALSE,FALSE),
  (2,'fire',0,'A',4,FALSE,FALSE,FALSE),
  (2,'fire',1,'B',6,FALSE,TRUE,FALSE),
  (2,'fire',2,'C',4,FALSE,FALSE,FALSE),
  (2,'fire',3,'B',5,FALSE,FALSE,TRUE),
  (2,'flash',0,'A',7,TRUE,FALSE,FALSE),
  (3,'ready',0,'A',1,FALSE,FALSE,FALSE),
  (3,'fire',0,'A',3,FALSE,FALSE,FALSE),
  (3,'fire',1,'A',7,FALSE,TRUE,FALSE),
  (3,'fire',2,'B',5,FALSE,FALSE,FALSE),
  (3,'fire',3,'C',5,FALSE,FALSE,FALSE),
  (3,'fire',4,'D',4,FALSE,FALSE,FALSE),
  (3,'fire',5,'C',5,FALSE,FALSE,FALSE),
  (3,'fire',6,'B',5,FALSE,FALSE,FALSE),
  (3,'fire',7,'A',3,FALSE,FALSE,TRUE),
  (3,'fire',8,'A',7,FALSE,FALSE,FALSE),
  (3,'flash',0,'A',4,TRUE,FALSE,FALSE),
  (3,'flash',1,'B',3,TRUE,FALSE,FALSE),
  (4,'ready',0,'A',1,FALSE,FALSE,FALSE),
  (4,'fire',0,'A',4,FALSE,TRUE,FALSE),
  (4,'fire',1,'B',4,FALSE,TRUE,FALSE),
  (4,'fire',2,'B',0,FALSE,FALSE,TRUE),
  (4,'flash',0,'A',5,TRUE,FALSE,FALSE),
  (5,'ready',0,'A',1,FALSE,FALSE,FALSE),
  (5,'fire',0,'B',8,FALSE,FALSE,FALSE),
  (5,'fire',1,'B',12,FALSE,TRUE,FALSE),
  (5,'fire',2,'B',0,FALSE,FALSE,TRUE),
  (5,'flash',0,'A',3,TRUE,FALSE,FALSE),
  (5,'flash',1,'B',4,TRUE,FALSE,FALSE),
  (5,'flash',2,'C',4,TRUE,FALSE,FALSE),
  (5,'flash',3,'D',4,TRUE,FALSE,FALSE),
  (6,'ready',0,'A',1,FALSE,FALSE,FALSE),
  (6,'fire',0,'A',3,FALSE,TRUE,FALSE),
  (6,'fire',1,'B',20,FALSE,FALSE,TRUE),
  (6,'flash',0,'A',4,TRUE,FALSE,FALSE),
  (7,'ready',0,'A',1,FALSE,FALSE,FALSE),
  (7,'fire',0,'A',20,FALSE,FALSE,FALSE),
  (7,'fire',1,'B',10,FALSE,FALSE,FALSE),
  (7,'fire',2,'B',10,FALSE,TRUE,FALSE),
  (7,'fire',3,'B',20,FALSE,FALSE,TRUE),
  (7,'flash',0,'A',11,TRUE,FALSE,FALSE),
  (7,'flash',1,'B',6,TRUE,FALSE,FALSE),
  (8,'ready',0,'C',4,FALSE,FALSE,FALSE),
  (8,'fire',0,'A',4,FALSE,TRUE,FALSE),
  (8,'fire',1,'B',4,FALSE,TRUE,FALSE),
  (8,'fire',2,'B',0,FALSE,FALSE,TRUE);

INSERT INTO level_pars (episode,level,par_secs) VALUES
  (1,1,30),
  (1,2,75),
  (1,3,120),
  (1,4,90),
  (1,5,165),
  (1,6,180),
  (1,7,180),
  (1,8,30),
  (1,9,165),
  (2,1,90),
  (2,2,90),
  (2,3,90),
  (2,4,120),
  (2,5,90),
  (2,6,360),
  (2,7,240),
  (2,8,30),
  (2,9,170),
  (3,1,90),
  (3,2,45),
  (3,3,90),
  (3,4,150),
  (3,5,90),
  (3,6,90),
  (3,7,165),
  (3,8,30),
  (3,9,135);

INSERT INTO boss_actions (map_name,boss_type,action) VALUES
  ('E1M8',3003,'lower_666'),   -- Barons of Hell
  ('E2M8',16,  'exit_level'),  -- Cyberdemon
  ('E3M8',7,   'exit_level'),  -- Spider Mastermind
  ('E4M8',7,   'lower_666');   -- Spider Mastermind

INSERT INTO finale_defs (episode,flat,patch,story_text) VALUES
  (1,'FLOOR4_8','CREDIT',
  E'Once you beat the big badasses and\n' ||
  E'clean out the moon base you''re supposed\n' ||
  E'to win, aren''t you? Aren''t you? Where''s\n' ||
  E'your fat reward and ticket home? What\n' ||
  E'the hell is this? It''s not supposed to\n' ||
  E'end this way!\n' ||
  E'\n' ||
  E'It stinks like rotten meat, but looks\n' ||
  E'like the lost Deimos base.  Looks like\n' ||
  E'you''re stuck on The Shores of Hell.\n' ||
  E'The only way out is through.\n' ||
  E'\n' ||
  E'To continue the DOOM experience, play\n' ||
  E'The Shores of Hell and its amazing\n' ||
  E'sequel, Inferno!\n'),
  (2,'SFLR6_1','VICTORY2',
  E'You''ve done it! The hideous cyber-\n' ||
  E'demon lord that ruled the lost Deimos\n' ||
  E'moon base has been slain and you\n' ||
  E'are triumphant! But ... where are\n' ||
  E'you? You clamber to the edge of the\n' ||
  E'moon and look down to see the awful\n' ||
  E'truth.\n' ||
  E'\n' ||
  E'Deimos floats above Hell itself!\n' ||
  E'You''ve never heard of anyone escaping\n' ||
  E'from Hell, but you''ll make the bastards\n' ||
  E'sorry they ever heard of you! Quickly,\n' ||
  E'you rappel down to  the surface of\n' ||
  E'Hell.\n' ||
  E'\n' ||
  E'Now, it''s on to the final chapter of\n' ||
  E'DOOM! -- Hell on Earth.'),
  (3,'MFLR8_4','PFUB1',
  E'The loathsome spiderdemon that\n' ||
  E'masterminded the invasion of the moon\n' ||
  E'bases and caused so much death has had\n' ||
  E'its ass kicked for all time.\n' ||
  E'\n' ||
  E'A hidden doorway opens and you enter.\n' ||
  E'You''ve proven too tough for Hell to\n' ||
  E'contain, and now Hell at last plays\n' ||
  E'fair -- for you emerge from the door\n' ||
  E'to see the green fields of Earth!\n' ||
  E'Home at last.\n' ||
  E'\n' ||
  E'You wonder what''s been happening on\n' ||
  E'Earth while you were battling evil\n' ||
  E'unleashed. It''s good that no Hell-\n' ||
  E'spawn could have come through that\n' ||
  E'door with you ...'),
  (4,'MFLR8_3','ENDPIC',
  E'the spider mastermind must have sent forth\n' ||
  E'its legions of hellspawn before your\n' ||
  E'final confrontation with that terrible\n' ||
  E'beast from hell.  but you stepped forward\n' ||
  E'and brought forth eternal damnation and\n' ||
  E'suffering upon the horde as a true hero\n' ||
  E'would in the face of something so evil.\n' ||
  E'\n' ||
  E'besides, someone was gonna pay for what\n' ||
  E'happened to daisy, your pet rabbit.\n' ||
  E'\n' ||
  E'but now, you see spread before you more\n' ||
  E'potential pain and gibbitude as a nation\n' ||
  E'of demons run amok among our cities.\n' ||
  E'\n' ||
  E'next stop, hell on earth!');

INSERT INTO line_special_defs
  (special,name,mechanic,cross_activated,cross_once,use_activated,use_once,
   key_required,is_exit,secret_exit,door_target,height_target,change_tex,
   flips_switch,shoot_activated,monster_usable,monster_crossable,scrolls,target_light,mover_type,direction,
   speed,wait_tics,step_height,crush,light_source,stops_mover) VALUES
  (  1,'DR Door Open Wait Close'             ,'door'    ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,'back' ,NULL            ,FALSE,FALSE,FALSE,TRUE ,FALSE,FALSE,NULL,'door_manual_raise' , 1, 2, 150,NULL,FALSE,NULL,NULL),
  (  2,'W1 Door Open Stay'                   ,'door'    ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_open'         , 1, 2, 150,NULL,FALSE,NULL,NULL),
  (  5,'W1 Floor Raise To Lowest Ceiling'    ,'raise'   ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest_ceiling',FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'       , 1, 1,   0,NULL,FALSE,NULL,NULL),
  (  7,'S1 Stairs Raise 8'                   ,'stairs'  ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,NULL            ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,NULL                ,NULL,1,NULL,8,FALSE,NULL,NULL),
  (  8,'W1 Stairs Raise 8'                   ,'stairs'  ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,NULL                ,NULL,1,NULL,8,FALSE,NULL,NULL),
  (  9,'S1 Donut'                            ,'donut'   ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,NULL            ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,NULL                ,NULL,NULL,NULL,NULL,FALSE,NULL,NULL),
  ( 11,'S1 Exit Level'                       ,NULL      ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,TRUE ,FALSE,NULL   ,NULL            ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,NULL                ,NULL,NULL,NULL,NULL,FALSE,NULL,NULL),
  ( 16,'W1 Door Close Wait Open'             ,'door'    ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_close_open'   ,-1, 2,1050,NULL,FALSE,NULL,NULL),
  ( 18,'S1 Floor Raise To Next Higher'       ,'raise'   ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,'next_floor'    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'       , 1, 1,   0,NULL,FALSE,NULL,NULL),
  ( 20,'S1 Floor Raise To Next Higher Change','raise'   ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,'next_floor'    ,TRUE ,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'       , 1, 0.5,   0,NULL,FALSE,NULL,NULL),
  ( 22,'W1 Floor Raise To Next Higher Change','raise'   ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'next_floor'    ,TRUE ,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'       , 1, 0.5,   0,NULL,FALSE,NULL,NULL),
  ( 23,'S1 Floor Lower To Lowest'            ,'floor'   ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,'lowest'        ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_lower'       ,-1, 1,   0,NULL,FALSE,NULL,NULL),
  ( 26,'DR Door Blue Key'                    ,'door'    ,FALSE,FALSE,TRUE ,FALSE,'blue'   ,FALSE,FALSE,'back' ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_manual_raise' , 1, 2, 150,NULL,FALSE,NULL,NULL),
  ( 27,'DR Door Yellow Key'                  ,'door'    ,FALSE,FALSE,TRUE ,FALSE,'yellow' ,FALSE,FALSE,'back' ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_manual_raise' , 1, 2, 150,NULL,FALSE,NULL,NULL),
  ( 28,'DR Door Red Key'                     ,'door'    ,FALSE,FALSE,TRUE ,FALSE,'red'    ,FALSE,FALSE,'back' ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_manual_raise' , 1, 2, 150,NULL,FALSE,NULL,NULL),
  ( 31,'D1 Door Open Stay'                   ,'door'    ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,'back' ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_open'         , 1, 2, 150,NULL,FALSE,NULL,NULL),
  ( 32,'D1 Door Blue Key'                    ,'door'    ,FALSE,FALSE,TRUE ,TRUE ,'blue'   ,FALSE,FALSE,'back' ,NULL            ,FALSE,FALSE,FALSE,TRUE ,FALSE,FALSE,NULL,'door_open'         , 1, 2, 150,NULL,FALSE,NULL,NULL),
  ( 33,'D1 Door Red Key'                     ,'door'    ,FALSE,FALSE,TRUE ,TRUE ,'red'    ,FALSE,FALSE,'back' ,NULL            ,FALSE,FALSE,FALSE,TRUE ,FALSE,FALSE,NULL,'door_open'         , 1, 2, 150,NULL,FALSE,NULL,NULL),
  ( 34,'D1 Door Yellow Key'                  ,'door'    ,FALSE,FALSE,TRUE ,TRUE ,'yellow' ,FALSE,FALSE,'back' ,NULL            ,FALSE,FALSE,FALSE,TRUE ,FALSE,FALSE,NULL,'door_open'         , 1, 2, 150,NULL,FALSE,NULL,NULL),
  ( 35,'W1 Lights To 35'                     ,'lights'  ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,  35,NULL                ,NULL,NULL,NULL,NULL,FALSE,NULL,NULL),
  ( 36,'W1 Floor Lower Turbo'                ,'floor'   ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'highest8'      ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_lower'       ,-1, 4,   0,NULL,FALSE,NULL,NULL),
  ( 38,'W1 Floor Lower To Lowest'            ,'floor'   ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest'        ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_lower'       ,-1, 1,   0,NULL,FALSE,NULL,NULL),
  ( 39,'W1 Teleport'                         ,'teleport',TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL            ,FALSE,FALSE,FALSE,FALSE,TRUE ,FALSE,NULL,NULL                ,NULL,NULL,NULL,NULL,FALSE,NULL,NULL),
  ( 46,'GR Door Open Stay'                   ,'door'    ,FALSE,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL            ,FALSE,TRUE ,TRUE ,FALSE,FALSE,FALSE,NULL,'door_open'         , 1, 2, 150,NULL,FALSE,NULL,NULL),
  ( 51,'S1 Secret Exit'                      ,NULL      ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,TRUE ,TRUE ,NULL   ,NULL            ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,NULL                ,NULL,NULL,NULL,NULL,FALSE,NULL,NULL),
  ( 52,'W1 Exit Level'                       ,NULL      ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,TRUE ,FALSE,NULL   ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,NULL                ,NULL,NULL,NULL,NULL,FALSE,NULL,NULL),
  ( 62,'SR Lift'                             ,'platform',FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest'        ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'platform'          ,-1, 4, 105,NULL,FALSE,NULL,NULL),
  ( 63,'SR Door Open Wait Close'             ,'door'    ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL            ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_raise'        , 1, 2, 150,NULL,FALSE,NULL,NULL),
  ( 70,'SR Floor Lower Turbo'                ,'floor'   ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,NULL   ,'highest8'      ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_lower'       ,-1, 4,   0,NULL,FALSE,NULL,NULL),
  ( 76,'WR Door Close Wait Open'             ,'door'    ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_close_open'   ,-1, 2,1050,NULL,FALSE,NULL,NULL),
  ( 82,'WR Floor Lower To Lowest'            ,'floor'   ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest'        ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_lower'       ,-1, 1,   0,NULL,FALSE,NULL,NULL),
  ( 86,'WR Door Open Stay'                   ,'door'    ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_open'         , 1, 2, 150,NULL,FALSE,NULL,NULL),
  ( 88,'WR Lift'                             ,'platform',TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest'        ,FALSE,FALSE,FALSE,FALSE,TRUE ,FALSE,NULL,'platform'          ,-1, 4, 105,NULL,FALSE,NULL,NULL),
  ( 90,'WR Door Open Wait Close'             ,'door'    ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_raise'        , 1, 2, 150,NULL,FALSE,NULL,NULL),
  ( 91,'WR Floor Raise To Lowest Ceiling'    ,'raise'   ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest_ceiling',FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'       , 1, 1,   0,NULL,FALSE,NULL,NULL),
  ( 97,'WR Teleport'                         ,'teleport',TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL            ,FALSE,FALSE,FALSE,FALSE,TRUE ,FALSE,NULL,NULL                ,NULL,NULL,NULL,NULL,FALSE,NULL,NULL),
  ( 98,'WR Floor Lower Turbo'                ,'floor'   ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'highest8'      ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_lower'       ,-1, 4,   0,NULL,FALSE,NULL,NULL),
  (103,'S1 Door Open Stay'                   ,'door'    ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,'tag'  ,NULL            ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_open'         , 1, 2, 150,NULL,FALSE,NULL,NULL),
  (109,'W1 Door Open Blazing'                ,'door'    ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_open'         , 1, 8, 150,NULL,FALSE,NULL,NULL),
  (117,'DR Door Blazing'                     ,'door'    ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,'back' ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_manual_raise' , 1, 8, 150,NULL,FALSE,NULL,NULL),
  (118,'S1 Door Open Blazing'                ,'door'    ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,'back' ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_open'         , 1, 8, 150,NULL,FALSE,NULL,NULL),
  (124,'W1 Secret Exit'                      ,NULL      ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,TRUE ,TRUE ,NULL   ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,NULL                ,NULL,NULL,NULL,NULL,FALSE,NULL,NULL),
  ( 48,'Scrolling Wall Left'                  ,NULL      ,FALSE,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL            ,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE ,NULL,NULL                ,NULL,NULL,NULL,NULL,FALSE,NULL,NULL),
-- Everything episodes 2 to 4 reach for beyond E1's set, plus the siblings of
-- each type so the family is complete.
  (  3,'W1 Door Close Stay'                        ,'door'    ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_close'         ,  -1,   2,   0,NULL,FALSE,NULL,NULL),
  (  4,'W1 Door Open Wait Close'                   ,'door'    ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,FALSE,FALSE,FALSE,TRUE ,FALSE,NULL,'door_raise'         ,   1,   2, 150,NULL,FALSE,NULL,NULL),
  ( 29,'S1 Door Open Wait Close'                   ,'door'    ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_raise'         ,   1,   2, 150,NULL,FALSE,NULL,NULL),
  ( 42,'SR Door Close Stay'                        ,'door'    ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_close'         ,  -1,   2,   0,NULL,FALSE,NULL,NULL),
  ( 50,'S1 Door Close Stay'                        ,'door'    ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_close'         ,  -1,   2,   0,NULL,FALSE,NULL,NULL),
  ( 61,'SR Door Open Stay'                         ,'door'    ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_open'          ,   1,   2, 150,NULL,FALSE,NULL,NULL),
  ( 75,'WR Door Close Stay'                        ,'door'    ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_close'         ,  -1,   2,   0,NULL,FALSE,NULL,NULL),
  (105,'WR Door Open Wait Close Blazing'           ,'door'    ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_raise'         ,   1,   8, 150,NULL,FALSE,NULL,NULL),
  (106,'WR Door Open Stay Blazing'                 ,'door'    ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_open'          ,   1,   8, 150,NULL,FALSE,NULL,NULL),
  (107,'WR Door Close Blazing'                     ,'door'    ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_close'         ,  -1,   8,   0,NULL,FALSE,NULL,NULL),
  (108,'W1 Door Open Wait Close Blazing'           ,'door'    ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_raise'         ,   1,   8, 150,NULL,FALSE,NULL,NULL),
  (110,'W1 Door Close Blazing'                     ,'door'    ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'door_close'         ,  -1,   8,   0,NULL,FALSE,NULL,NULL),
  (111,'S1 Door Open Wait Close Blazing'           ,'door'    ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_raise'         ,   1,   8, 150,NULL,FALSE,NULL,NULL),
  (112,'S1 Door Open Stay Blazing'                 ,'door'    ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_open'          ,   1,   8, 150,NULL,FALSE,NULL,NULL),
  (113,'S1 Door Close Blazing'                     ,'door'    ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_close'         ,  -1,   8,   0,NULL,FALSE,NULL,NULL),
  (114,'SR Door Open Wait Close Blazing'           ,'door'    ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_raise'         ,   1,   8, 150,NULL,FALSE,NULL,NULL),
  (115,'SR Door Open Stay Blazing'                 ,'door'    ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_open'          ,   1,   8, 150,NULL,FALSE,NULL,NULL),
  (116,'SR Door Close Blazing'                     ,'door'    ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_close'         ,  -1,   8,   0,NULL,FALSE,NULL,NULL),
  ( 99,'SR Door Blue Open Stay Blazing'            ,'door'    ,FALSE,FALSE,TRUE ,FALSE,'blue'   ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_open'          ,   1,   8, 150,NULL,FALSE,NULL,NULL),
  (133,'S1 Door Blue Open Stay Blazing'            ,'door'    ,FALSE,FALSE,TRUE ,TRUE ,'blue'   ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_open'          ,   1,   8, 150,NULL,FALSE,NULL,NULL),
  (134,'SR Door Red Open Stay Blazing'             ,'door'    ,FALSE,FALSE,TRUE ,FALSE,'red'    ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_open'          ,   1,   8, 150,NULL,FALSE,NULL,NULL),
  (135,'S1 Door Red Open Stay Blazing'             ,'door'    ,FALSE,FALSE,TRUE ,TRUE ,'red'    ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_open'          ,   1,   8, 150,NULL,FALSE,NULL,NULL),
  (136,'SR Door Yellow Open Stay Blazing'          ,'door'    ,FALSE,FALSE,TRUE ,FALSE,'yellow' ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_open'          ,   1,   8, 150,NULL,FALSE,NULL,NULL),
  (137,'S1 Door Yellow Open Stay Blazing'          ,'door'    ,FALSE,FALSE,TRUE ,TRUE ,'yellow' ,FALSE,FALSE,'tag'  ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'door_open'          ,   1,   8, 150,NULL,FALSE,NULL,NULL),
  ( 19,'W1 Floor Lower To Highest'                 ,'floor'   ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'highest'               ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_lower'        ,  -1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 45,'SR Floor Lower To Highest'                 ,'floor'   ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,NULL   ,'highest'               ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_lower'        ,  -1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 83,'WR Floor Lower To Highest'                 ,'floor'   ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'highest'               ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_lower'        ,  -1,   1,   0,NULL,FALSE,NULL,NULL),
  (102,'S1 Floor Lower To Highest'                 ,'floor'   ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,'highest'               ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_lower'        ,  -1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 60,'SR Floor Lower To Lowest'                  ,'floor'   ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest'                ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_lower'        ,  -1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 71,'S1 Floor Lower Turbo'                      ,'floor'   ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,'highest8'              ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_lower'        ,  -1,   4,   0,NULL,FALSE,NULL,NULL),
  ( 37,'W1 Floor Lower To Lowest Change'           ,'floor'   ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest'                ,TRUE ,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_lower'        ,  -1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 84,'WR Floor Lower To Lowest Change'           ,'floor'   ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest'                ,TRUE ,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_lower'        ,  -1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 30,'W1 Floor Raise By Shortest Texture'        ,'raise'   ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'shortest_texture'      ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 96,'WR Floor Raise By Shortest Texture'        ,'raise'   ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'shortest_texture'      ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 58,'W1 Floor Raise 24'                         ,'raise'   ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'plus24'                ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 92,'WR Floor Raise 24'                         ,'raise'   ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'plus24'                ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 59,'W1 Floor Raise 24 Change'                  ,'raise'   ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'plus24'                ,TRUE ,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 93,'WR Floor Raise 24 Change'                  ,'raise'   ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'plus24'                ,TRUE ,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 14,'S1 Floor Raise 32 Change'                  ,'raise'   ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,'plus32'                ,TRUE ,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1, 0.5,   0,NULL,FALSE,NULL,NULL),
  ( 67,'SR Floor Raise 32 Change'                  ,'raise'   ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,NULL   ,'plus32'                ,TRUE ,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1, 0.5,   0,NULL,FALSE,NULL,NULL),
  ( 15,'S1 Floor Raise 24 Change'                  ,'raise'   ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,'plus24'                ,TRUE ,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1, 0.5,   0,NULL,FALSE,NULL,NULL),
  ( 66,'SR Floor Raise 24 Change'                  ,'raise'   ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,NULL   ,'plus24'                ,TRUE ,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1, 0.5,   0,NULL,FALSE,NULL,NULL),
  ( 56,'W1 Floor Raise To Lowest Ceiling -8 Crush' ,'raise'   ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest_ceiling_minus8' ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   1,   0,NULL,TRUE,NULL,NULL),
  ( 94,'WR Floor Raise To Lowest Ceiling -8 Crush' ,'raise'   ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest_ceiling_minus8' ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   1,   0,NULL,TRUE,NULL,NULL),
  ( 55,'S1 Floor Raise To Lowest Ceiling -8 Crush' ,'raise'   ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,'lowest_ceiling_minus8' ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   1,   0,NULL,TRUE,NULL,NULL),
  ( 65,'SR Floor Raise To Lowest Ceiling -8 Crush' ,'raise'   ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest_ceiling_minus8' ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   1,   0,NULL,TRUE,NULL,NULL),
  (101,'S1 Floor Raise To Lowest Ceiling'          ,'raise'   ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,'lowest_ceiling'        ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 64,'SR Floor Raise To Lowest Ceiling'          ,'raise'   ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest_ceiling'        ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 24,'G1 Floor Raise To Lowest Ceiling'          ,'raise'   ,FALSE,FALSE,FALSE,TRUE ,NULL     ,FALSE,FALSE,NULL   ,'lowest_ceiling'        ,FALSE,TRUE ,TRUE ,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 47,'G1 Floor Raise To Next Change'             ,'raise'   ,FALSE,FALSE,FALSE,TRUE ,NULL     ,FALSE,FALSE,NULL   ,'next_floor'            ,TRUE ,TRUE ,TRUE ,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1, 0.5,   0,NULL,FALSE,NULL,NULL),
  (119,'W1 Floor Raise To Next'                    ,'raise'   ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'next_floor'            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   1,   0,NULL,FALSE,NULL,NULL),
  (128,'WR Floor Raise To Next'                    ,'raise'   ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'next_floor'            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   1,   0,NULL,FALSE,NULL,NULL),
  (129,'W1 Floor Raise Turbo To Next'              ,'raise'   ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'next_floor'            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   4,   0,NULL,FALSE,NULL,NULL),
  (130,'WR Floor Raise Turbo To Next'              ,'raise'   ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'next_floor'            ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   4,   0,NULL,FALSE,NULL,NULL),
  (131,'S1 Floor Raise Turbo To Next'              ,'raise'   ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,'next_floor'            ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   4,   0,NULL,FALSE,NULL,NULL),
  (132,'SR Floor Raise Turbo To Next'              ,'raise'   ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,NULL   ,'next_floor'            ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   4,   0,NULL,FALSE,NULL,NULL),
  (140,'S1 Floor Raise 512'                        ,'raise'   ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,'plus512'               ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'floor_raise'        ,   1,   4,   0,NULL,FALSE,NULL,NULL),
  ( 10,'W1 Lift'                                   ,'platform',TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest'                ,FALSE,FALSE,FALSE,FALSE,TRUE ,FALSE,NULL,'platform'           ,  -1,   4, 105,NULL,FALSE,NULL,NULL),
  ( 21,'S1 Lift'                                   ,'platform',FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,'lowest'                ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'platform'           ,  -1,   4, 105,NULL,FALSE,NULL,NULL),
  (120,'WR Lift Blazing'                           ,'platform',TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest'                ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'platform'           ,  -1,   8, 105,NULL,FALSE,NULL,NULL),
  (121,'W1 Lift Blazing'                           ,'platform',TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest'                ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'platform'           ,  -1,   8, 105,NULL,FALSE,NULL,NULL),
  (122,'S1 Lift Blazing'                           ,'platform',FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,'lowest'                ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'platform'           ,  -1,   8, 105,NULL,FALSE,NULL,NULL),
  (123,'SR Lift Blazing'                           ,'platform',FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest'                ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'platform'           ,  -1,   8, 105,NULL,FALSE,NULL,NULL),
  ( 53,'W1 Platform Perpetual Raise'               ,'platform',TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest'                ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'platform_perpetual' ,  -1,   1, 105,NULL,FALSE,NULL,NULL),
  ( 87,'WR Platform Perpetual Raise'               ,'platform',TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'lowest'                ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'platform_perpetual' ,  -1,   1, 105,NULL,FALSE,NULL,NULL),
  ( 40,'W1 Ceiling Raise To Highest'               ,'ceiling' ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'highest_ceiling'       ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'ceiling_raise'      ,   1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 41,'S1 Ceiling Lower To Floor'                 ,'ceiling' ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,'floor'                 ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'ceiling_lower'      ,  -1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 43,'SR Ceiling Lower To Floor'                 ,'ceiling' ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,NULL   ,'floor'                 ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,'ceiling_lower'      ,  -1,   1,   0,NULL,FALSE,NULL,NULL),
  ( 44,'W1 Ceiling Lower To Floor+8 Crush'         ,'ceiling' ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'floor8'                ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'ceiling_lower'      ,  -1,   1,   0,NULL,TRUE,NULL,NULL),
  ( 72,'WR Ceiling Lower To Floor+8 Crush'         ,'ceiling' ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,'floor8'                ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'ceiling_lower'      ,  -1,   1,   0,NULL,TRUE,NULL,NULL),
  (  6,'W1 Ceiling Crusher Fast'                   ,'crusher' ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'crusher'            ,  -1,   2,   0,NULL,TRUE,NULL,NULL),
  ( 25,'W1 Ceiling Crusher'                        ,'crusher' ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'crusher'            ,  -1,   1,   0,NULL,TRUE,NULL,NULL),
  ( 73,'WR Ceiling Crusher'                        ,'crusher' ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'crusher'            ,  -1,   1,   0,NULL,TRUE,NULL,NULL),
  ( 77,'WR Ceiling Crusher Fast'                   ,'crusher' ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'crusher'            ,  -1,   2,   0,NULL,TRUE,NULL,NULL),
  (141,'W1 Ceiling Crusher Silent'                 ,'crusher' ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'crusher'            ,  -1,   1,   0,NULL,TRUE,NULL,NULL),
  ( 57,'W1 Ceiling Crusher Stop'                   ,'stop'    ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,NULL                 ,NULL,NULL,NULL,NULL,FALSE,NULL,'crusher'),
  ( 74,'WR Ceiling Crusher Stop'                   ,'stop'    ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,NULL                 ,NULL,NULL,NULL,NULL,FALSE,NULL,'crusher'),
  ( 54,'W1 Platform Stop'                          ,'stop'    ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,NULL                 ,NULL,NULL,NULL,NULL,FALSE,NULL,'platform_perpetual'),
  ( 89,'WR Platform Stop'                          ,'stop'    ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,NULL                 ,NULL,NULL,NULL,NULL,FALSE,NULL,'platform_perpetual'),
  ( 13,'W1 Lights To 255'                          ,'lights'  ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, 255,NULL                 ,NULL,NULL,NULL,NULL,FALSE,NULL,NULL),
  ( 81,'WR Lights To 255'                          ,'lights'  ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, 255,NULL                 ,NULL,NULL,NULL,NULL,FALSE,NULL,NULL),
  (138,'SR Lights To 255'                          ,'lights'  ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE, 255,NULL                 ,NULL,NULL,NULL,NULL,FALSE,NULL,NULL),
  (139,'SR Lights To 35'                           ,'lights'  ,FALSE,FALSE,TRUE ,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,  35,NULL                 ,NULL,NULL,NULL,NULL,FALSE,NULL,NULL),
  ( 79,'WR Lights To 35'                           ,'lights'  ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,  35,NULL                 ,NULL,NULL,NULL,NULL,FALSE,NULL,NULL),
  ( 12,'W1 Lights To Max Neighbor'                 ,'lights'  ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,NULL                 ,NULL,NULL,NULL,NULL,FALSE,'max_neighbor',NULL),
  ( 80,'WR Lights To Max Neighbor'                 ,'lights'  ,TRUE ,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,NULL                 ,NULL,NULL,NULL,NULL,FALSE,'max_neighbor',NULL),
  (104,'W1 Lights To Min Neighbor'                 ,'lights'  ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,NULL                 ,NULL,NULL,NULL,NULL,FALSE,'min_neighbor',NULL),
  ( 17,'W1 Lights Start Strobing'                  ,'lights'  ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,NULL                 ,NULL,NULL,NULL,NULL,FALSE,'strobe',NULL),
  (125,'W1 Teleport Monsters Only'                 ,'teleport',FALSE,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,TRUE ,FALSE,NULL,NULL                 ,NULL,NULL,NULL,NULL,FALSE,NULL,NULL),
  (126,'WR Teleport Monsters Only'                 ,'teleport',FALSE,FALSE,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,TRUE ,FALSE,NULL,NULL                 ,NULL,NULL,NULL,NULL,FALSE,NULL,NULL),
  (127,'S1 Stairs Raise 16 Turbo'                  ,'stairs'  ,FALSE,FALSE,TRUE ,TRUE ,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,TRUE ,FALSE,FALSE,FALSE,FALSE,NULL,NULL                 ,NULL,   4,NULL,16,FALSE,NULL,NULL),
  (100,'W1 Stairs Raise 16 Turbo'                  ,'stairs'  ,TRUE ,TRUE ,FALSE,FALSE,NULL     ,FALSE,FALSE,NULL   ,NULL                    ,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NULL,NULL                 ,NULL,   4,NULL,16,FALSE,NULL,NULL);
INSERT INTO thing_sound_defs (thing_type,cue,variant,sound_name) VALUES
  (   1,'death',0,'DSPLDETH'),
  (   1,'pain',0,'DSPLPAIN'),
  (   9,'active',0,'DSPOSACT'),
  (   9,'death',0,'DSPODTH1'),
  (   9,'death',1,'DSPODTH2'),
  (   9,'death',2,'DSPODTH3'),
  (   9,'pain',0,'DSPOPAIN'),
  (   9,'sight',0,'DSPOSIT1'),
  (   9,'sight',1,'DSPOSIT2'),
  (   9,'sight',2,'DSPOSIT3'),
  (  58,'active',0,'DSDMACT'),
  (  58,'death',0,'DSSGTDTH'),
  (  58,'pain',0,'DSDMPAIN'),
  (  58,'sight',0,'DSSGTSIT'),
  (3001,'active',0,'DSBGACT'),
  (3001,'death',0,'DSBGDTH1'),
  (3001,'death',1,'DSBGDTH2'),
  (3001,'pain',0,'DSPOPAIN'),
  (3001,'sight',0,'DSBGSIT1'),
  (3001,'sight',1,'DSBGSIT2'),
  (3002,'active',0,'DSDMACT'),
  (3002,'death',0,'DSSGTDTH'),
  (3002,'pain',0,'DSDMPAIN'),
  (3002,'sight',0,'DSSGTSIT'),
  (3003,'active',0,'DSDMACT'),
  (3003,'death',0,'DSBRSDTH'),
  (3003,'pain',0,'DSDMPAIN'),
  (3003,'sight',0,'DSBRSSIT'),
  (3004,'active',0,'DSPOSACT'),
  (3004,'death',0,'DSPODTH1'),
  (3004,'death',1,'DSPODTH2'),
  (3004,'death',2,'DSPODTH3'),
  (3004,'pain',0,'DSPOPAIN'),
  (3004,'sight',0,'DSPOSIT1'),
  (3004,'sight',1,'DSPOSIT2'),
  (3004,'sight',2,'DSPOSIT3'),
  (3004,'xdeath',0,'DSSLOP'),
  (9,'xdeath',0,'DSSLOP'),
  (3001,'xdeath',0,'DSSLOP');
INSERT INTO thing_sound_defs (thing_type,cue,variant,sound_name) VALUES
  (3005,'sight',0,'DSCACSIT'),
  (3005,'active',0,'DSDMACT'),
  (3005,'pain',0,'DSDMPAIN'),
  (3005,'death',0,'DSCACDTH'),
  (3006,'active',0,'DSDMACT'),
  (3006,'pain',0,'DSDMPAIN'),
  (3006,'death',0,'DSFIRXPL'),
  (  16,'sight',0,'DSCYBSIT'),
  (  16,'active',0,'DSDMACT'),
  (  16,'pain',0,'DSDMPAIN'),
  (  16,'death',0,'DSCYBDTH'),
  (   7,'sight',0,'DSSPISIT'),
  (   7,'active',0,'DSDMACT'),
  (   7,'pain',0,'DSDMPAIN'),
  (   7,'death',0,'DSSPIDTH');


INSERT INTO pickup_messages (thing_type,message) VALUES
  (5,'Picked up a blue keycard.'),
  (6,'Picked up a yellow keycard.'),
  (8,'Picked up a backpack full of ammo!'),
  (13,'Picked up a red keycard.'),
  (38,'Picked up a red skull key.'),
  (39,'Picked up a yellow skull key.'),
  (40,'Picked up a blue skull key.'),
  (2022,'Invulnerability!'),
  (17,'Picked up an energy cell pack.'),
  (2001,'You got the shotgun!'),
  (2002,'You got the chaingun!'),
  (2003,'You got the rocket launcher!'),
  (2004,'You got the plasma gun!'),
  (2005,'A chainsaw!  Find some meat!'),
  (2006,'You got the BFG9000!  Oh, yes.'),
  (2007,'Picked up a clip.'),
  (2008,'Picked up 4 shotgun shells.'),
  (2010,'Picked up a rocket.'),
  (2011,'Picked up a stimpack.'),
  (2012,'Picked up a medikit.'),
  (2013,'Supercharge!'),
  (2014,'Picked up a health bonus.'),
  (2015,'Picked up an armor bonus.'),
  (2018,'Picked up the armor.'),
  (2019,'Picked up the MegaArmor!'),
  (2023,'Berserk!'),
  (2024,'Partial Invisibility'),
  (2025,'Radiation Shielding Suit'),
  (2026,'Computer Area Map'),
  (2045,'Light Amplification Visor'),
  (2046,'Picked up a box of rockets.'),
  (2047,'Picked up an energy cell.'),
  (2048,'Picked up a box of bullets.'),
  (2049,'Picked up a box of shotgun shells.');

-- Doom's #defines, read by the runtime through doom_const().
INSERT INTO doom_constants (name, value, source) VALUES
  ('FRICTION', 0.90625, '0xe800/65536, p_mobj.c: momentum kept per tic on the ground'),
  ('STOPSPEED', 0.0625, '0x1000/65536, p_mobj.c: below this a thing stands still'),
  ('MAXMOVE', 30, '30*FRACUNIT, p_local.h: momentum is clamped to this'),
  ('MAXSTEP', 24, '24*FRACUNIT, P_TryMove: the highest step a thing climbs'),
  ('VIEWHEIGHT', 41, '41*FRACUNIT, p_local.h: the eye above the floor'),
  ('PLAYER_HEIGHT', 56, 'mobjinfo MT_PLAYER height'),
  ('PLAYER_RADIUS', 16, 'mobjinfo MT_PLAYER radius'),
  ('FORWARDMOVE', 25, '0x19, forwardmove[0], g_game.c'),
  ('FORWARDMOVE_RUN', 50, '0x32, forwardmove[1]'),
  ('SIDEMOVE', 24, '0x18, sidemove[0]'),
  ('SIDEMOVE_RUN', 40, '0x28, sidemove[1]'),
  ('THRUST_UNIT', 0.03125, '2048/65536: P_MovePlayer thrusts cmd->forwardmove*2048'),
  ('MELEE_REACH', 68, 'this engine: MELEERANGE (64) plus a margin, one number for every biter'),
  ('USERANGE', 64, '64*FRACUNIT, p_local.h: how far P_UseLines reaches'),
  ('MAXBOB', 16, '0x100000, p_local.h: the view bob is clamped here'),
  ('GRAVITY', 1, 'FRACUNIT, p_local.h: one unit a tic, squared'),
  ('BOB_FACTOR', 4, 'p_user.c: player->bob is the squared momentum >> 2'),
  ('BOB_PERIOD_TICS', 20, 'p_user.c: FINEANGLES/20*leveltime, so the bob repeats every 20 tics'),
  ('BLOCK_MARGIN', 2, 'this engine: slack on the bounding box that stands in for the blockmap'),
  ('DROPPED_THING_ID_BASE', 100000, 'this engine: Things at or above this id were dropped by a monster, not placed by the WAD'),
  ('PICKUP_REACH', 36, 'P_TouchSpecialThing: the player radius plus an item radius'),
  ('BONUSADD', 6, 'BONUSADD, p_local.h: the gold blink per item taken'),
  ('MESSAGE_TICS', 140, 'HU_MSGTIMEOUT, 4*TICRATE: how long a pickup line stays up'),
  ('ATTACK_Z_OFFSET', 8, '8*FRACUNIT, P_LineAttack: a shot leaves the eye this far above mid-height'),
  ('AIM_SPREAD_DEGREES', 5.625, '1<<26 in BAM, P_BulletSlope: autoaim tries straight ahead then this far either side'),
  ('AUTOAIM_SLOPE', 0.625, '100*FRACUNIT/160, P_AimLineAttack: the vertical half-cone autoaim searches'),
  ('SLOPE_UNBOUNDED', 1000000, 'this engine: stands in for an unlimited aim window before any line narrows it'),
  ('GUNSHOT_SPREAD_UNITS', 16384, '(P_Random()-P_Random())<<18 as a fraction of a full turn, P_GunShot'),
  ('MISSILE_SPAWN_Z', 32, '4*8*FRACUNIT, P_SpawnMissile: a missile leaves this far above the floor'),
  ('SHADOW_SPREAD_UNITS', 4096, '(P_Random()-P_Random())<<20 as a fraction of a full turn, MF_SHADOW aim'),
  ('PROJECTILE_EFFECT_ID_BASE', 3000000000000, 'this engine: the world_effects id range projectile impacts own'),
  ('MISSILE_SPAWN_AHEAD', 20, 'this engine: a missile starts this far in front of its shooter so it cannot hit them'),
  ('NIGHTMARE_MISSILE_SPEED', 20, 'G_InitNew: fast missiles, every monster missile raised to this on Nightmare'),
  ('AUTOMAP_WORLD_HEIGHT', 2048, 'Map units spanned by the screen height at zoom 1'),
  ('AUTOMAP_MIN_ZOOM', 0.125, 'Furthest out the automap will go'),
  ('AUTOMAP_MAX_ZOOM', 8, 'Closest in the automap will go'),
  ('SOUND_TRIM_AGE_TICS', 70, 'Positional sound cues older than two seconds have been read by every client; the referee used to delete them once a second'),
  ('SOUND_TRIM_INTERVAL_TICS', 35, 'How often the trim runs, in tics -- once a second, as the referee timer did'),
  ('ACTIVE_SOUND_ODDS', 320, 'A_Chase rolls P_Random()<3 per call and its see frames average ~5 tics, so about one tic in 400; this engine rolls per tic'),
  ('MIN_WALK_OPENING', 56, 'this engine: the opening anything needs to walk through, where vanilla P_Move uses the thing''s own height'),
  ('DEFAULT_ATTACK_RANGE', 2048, 'MISSILERANGE, 32*64*FRACUNIT: how far a shot carries when the catalogue gives no range'),
  ('HITSCAN_SPREAD_UNITS', 4096, '(P_Random()-P_Random())<<20 as a fraction of a full turn, A_PosAttack'),
  ('SHADOW_MISS_UNITS', 2048, '<<21, the extra error a shot picks up against an MF_SHADOW target'),
  ('SKULL_CHARGE_SPEED', 20, 'SKULLSPEED, 20*FRACUNIT: A_SkullAttack hurls a lost soul this fast'),
  ('SKULL_HIT_REACH', 36, 'this engine: the box a charging lost soul lands its hit in'),
  ('BLOCKMAP_CELL', 128, 'MAPBLOCKUNITS, p_local.h: the grid the thing-collision broad phase buckets into'),
  ('DAMAGE_FLOOR_INTERVAL', 32, 'P_PlayerInSpecialSector: a damaging floor bites once every 32 tics'),
  ('EFFECT_ID_TIC_SPAN', 4096, 'this engine: world_effects ids pack a tic into this many slots per source'),
  ('ITEM_FOG_EFFECT_ID_BASE', 4000000000, 'this engine: the world_effects id range item respawns own'),
  ('MONSTER_RESPAWN_EFFECT_ID_BASE', 4100000000, 'this engine: the range nightmare monster respawns own'),
  ('PLAYER_RESPAWN_EFFECT_ID_BASE', 4200000000, 'this engine: the range deathmatch player respawns own'),
  ('SIGHT_RANGE', 1200, 'this engine: P_LookForPlayers has no range, this one does'),
  ('TICRATE', 35, '35 tics a second'),
  ('TURN_DEGREES_PER_TIC', 3.2, 'angleturn[1] 640<<16 per tic, g_game.c: the keyboard turn'),
  ('ITEM_RESPAWN_TICS', 1050, '30*TICRATE, P_RespawnSpecials'),
  ('MONSTER_RESPAWN_TICS', 420, '12*TICRATE, P_NightmareRespawn'),
  ('CHASE_AXIS_DEADBAND', 10, '10*FRACUNIT, P_NewChaseDir: nearer than this on an axis and that axis has no preference'),
  ('CHASE_SWAP_CHANCE', 200, 'P_NewChaseDir: P_Random() > 200 tries the other axis first'),
  ('CHASE_MOVECOUNT_MASK', 15, 'P_TryWalk: movecount = P_Random()&15'),
  ('MONSTER_STEP', 8, 'this engine: one walk stride for every monster, where vanilla uses mobjinfo speed'),
  ('POS_EPSILON', 0.0000001, 'this engine: a float position within this of the last one counts as unmoved'),
  ('PSPRITE_EPSILON', 0.001, 'this engine: a psprite offset within this of its rest counts as at rest'),
  ('PSPRITE_REST_X', 1.0, 'p_pspr.c: the ready weapon rests at this sx'),
  ('PSPRITE_REST_Y', 32.0, 'WEAPONTOP, p_pspr.c: and at this sy')
ON CONFLICT (name) DO UPDATE SET value = EXCLUDED.value, source = EXCLUDED.source;
