#!/usr/bin/env python3
"""Freeze recorded demos into sql/loader/demo_data.sql so they survive a rebuild.

Demos live in the database, and the database gets thrown away and rebuilt from
the WAD whenever the schema changes. Anything meant to ship -- an attract-mode
playthrough, a demo a regression test replays -- has to be seeded like the rest
of the catalogues instead.

Record in the game with F9, then:

    python3 scripts/gen_demo_data.py --dsn "..." e1m1-attract e1m3-demo

With no names it takes every demo currently in the database. Demo ids are
renumbered from 1 so the generated file does not churn.
"""
import argparse

import psycopg2

OUT = "sql/loader/demo_data.sql"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dsn", required=True)
    ap.add_argument("names", nargs="*", help="demo names; default is all")
    ap.add_argument("--out", default=OUT)
    args = ap.parse_args()

    conn = psycopg2.connect(args.dsn)
    conn.autocommit = True
    cur = conn.cursor()
    if args.names:
        cur.execute(
            "SELECT demo_id,name,map_id,player_thing_id,skill,tic_count"
            " FROM demos WHERE name = ANY(%s) ORDER BY name", (args.names,))
    else:
        cur.execute(
            "SELECT demo_id,name,map_id,player_thing_id,skill,tic_count"
            " FROM demos ORDER BY name")
    demos = cur.fetchall()
    if not demos:
        raise SystemExit("no demos matched")

    out = [
        "-- GENERATED by scripts/gen_demo_data.py -- do not edit by hand.",
        "--",
        "-- Recorded playthroughs, seeded with the rest of the catalogues so a",
        "-- rebuilt database still has them. A demo is the input stream, one",
        "-- row per tic; the world is recomputed from it, which only works",
        "-- because the simulation is reproducible (see doom_prandom).",
        "--",
        "-- Re-record in the game with F9, then re-run the generator.",
        "",
        "TRUNCATE demos;",
        "TRUNCATE demo_tics;",
        "",
        "INSERT INTO demos"
        " (demo_id,name,map_id,player_thing_id,skill,tic_count) VALUES",
    ]
    rows = []
    for new_id, (_, name, map_id, player, skill, tics) in enumerate(demos, 1):
        rows.append(f"  ({new_id},'{name}',{map_id},{player},{skill},{tics})")
    out.append(",\n".join(rows) + ";")

    total = 0
    for new_id, (old_id, name, *_rest) in enumerate(demos, 1):
        cur.execute(
            "SELECT tic,move_fwd,move_strafe,running,turn_degrees,attack_held,"
            " weapon_switch_to,use_requested FROM demo_tics"
            " WHERE demo_id=%s ORDER BY tic", (old_id,))
        tics = cur.fetchall()
        total += len(tics)
        out.append("")
        out.append(f"-- {name}: {len(tics)} tics")
        out.append(
            "INSERT INTO demo_tics (demo_id,tic,move_fwd,move_strafe,running,"
            "turn_degrees,attack_held,weapon_switch_to,use_requested) VALUES")
        body = []
        for tic, fwd, strafe, run, turn, atk, weapon, use in tics:
            # Full precision, not a tidy %.4f. These are REAL columns, and a
            # demo is only worth seeding if the seeded stream is bit-for-bit
            # the recorded one -- rounding the turn by a ten-thousandth of a
            # degree is enough to send the player into a different wall by the
            # end of a minute's play. %.9g round-trips float32 exactly.
            body.append(
                f"  ({new_id},{tic},{fwd:.9g},{strafe:.9g},"
                f"{'TRUE' if run else 'FALSE'},{turn:.9g},"
                f"{'TRUE' if atk else 'FALSE'},"
                f"{'NULL' if weapon is None else weapon},"
                f"{'TRUE' if use else 'FALSE'})")
        out.append(",\n".join(body) + ";")

    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out) + "\n")
    print(f"wrote {args.out}: {len(demos)} demo(s), {total} tics")
    for new_id, (_, name, map_id, _p, skill, tics) in enumerate(demos, 1):
        print(f"   {new_id}. {name}  map {map_id}, skill {skill}, {tics} tics")


if __name__ == "__main__":
    main()
