#!/usr/bin/env python3
"""Generate sql/runtime/functions/32_save_load.sql from the live schema.

The save mirrors are created with CREATE TABLE AS, so they always have their
source's columns -- but CedarDB has no `SELECT * EXCEPT (slot)`, so restoring
needs the column list spelled out. Generating it from information_schema keeps
it exact; re-run this after changing any saved table.
"""
import sys
import psycopg2

SAVED = ("player_state", "player_weapons", "player_weapon_owned", "things",
         "thing_health", "monster_ai", "monster_projectiles", "world_effects",
         "sectors", "sidedefs", "sector_movers", "line_buttons",
         "line_activations", "picked_up_items", "level_secret_discoveries",
         "level_stats")
# Rebuilt on load rather than stored.
TRANSIENT = ("game_tic_commands", "line_special_events", "line_use_results",
             "pickup_touches", "pickup_grants", "sound_events",
             "hitscan_hits", "projectile_damage", "projectile_impacts",
             "monster_attack_damage")
OUT = "sql/runtime/functions/32_save_load.sql"


def columns(cur, table):
    cur.execute(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_name=%s ORDER BY ordinal_position", (table,))
    return [r[0] for r in cur.fetchall()]


def main():
    conn = psycopg2.connect(sys.argv[1])
    conn.autocommit = True
    cur = conn.cursor()
    cols = {t: columns(cur, t) for t in SAVED}
    missing = [t for t, c in cols.items() if not c]
    if missing:
        raise SystemExit(f"no such tables: {missing}")

    out = ['-- GENERATED by scripts/gen_save_load.py -- do not edit by hand.',
           '-- Re-run it after changing the schema of any saved table.',
           '--',
           '-- Both functions are single CedarScript bodies, and a function',
           '-- call is one transaction: a failure part-way through rolls the',
           '-- whole save or load back, verified under autocommit as well as',
           '-- inside an explicit BEGIN. So a torn save cannot be observed.',
           '']
    # ---------------- save ----------------
    out.append("CREATE OR REPLACE FUNCTION doom_save_game("
               "p_slot integer, p_map_id integer, p_player_thing_id integer, "
               "p_skill integer, p_name text) RETURNS integer")
    out.append("LANGUAGE cedarscript AS $doom$")
    out.append("DELETE FROM save_slots WHERE slot=p_slot::int;")
    out.append("INSERT INTO save_slots "
               "(slot,saved_at,name,map_id,player_thing_id,map_name,skill)")
    out.append("SELECT p_slot::int, NOW(), p_name::text, p_map_id::int,")
    out.append("       p_player_thing_id::int,")
    out.append("       (SELECT m.name FROM maps m WHERE m.map_id=p_map_id::int),")
    out.append("       -- The skill the WORLD was built with, taken from")
    out.append("       -- level_stats rather than the caller. reset_stage seeds")
    out.append("       -- thing_health/monster_ai per skill, so a save that")
    out.append("       -- recorded a different skill than its own world loaded")
    out.append("       -- with monsters that had no health and no AI row: they")
    out.append("       -- rendered alive, never attacked, and cost frame time.")
    out.append("       COALESCE((SELECT ls.skill_bit FROM level_stats ls")
    out.append("                  WHERE ls.map_id=p_map_id::int")
    out.append("                    AND ls.player_thing_id=p_player_thing_id::int),")
    out.append("                p_skill::int);")
    for t in SAVED:
        cl = ",".join(cols[t])
        out.append(f"\nDELETE FROM save_{t} WHERE slot=p_slot::int;")
        out.append(f"INSERT INTO save_{t} (slot,{cl})")
        out.append(f"SELECT p_slot::int,{cl} FROM {t} WHERE map_id=p_map_id::int;")
    out.append("\nreturn p_slot::int;")
    out.append("$doom$;")
    # ---------------- load ----------------
    out.append("")
    out.append("CREATE OR REPLACE FUNCTION doom_load_game(p_slot integer) "
               "RETURNS integer")
    out.append("LANGUAGE cedarscript AS $doom$")
    out.append("-- Returns the restored map_id, or -1 when the slot is empty.")
    out.append("let mut target = -1;")
    out.append("SELECT COALESCE(MIN(map_id),-1) AS m FROM save_slots "
               "WHERE slot=p_slot::int")
    out.append("{ target = m; }")
    out.append("if target >= 0 {")
    for t in SAVED:
        cl = ",".join(cols[t])
        out.append(f"  DELETE FROM {t} WHERE map_id=target;")
        out.append(f"  INSERT INTO {t} ({cl})")
        out.append(f"  SELECT {cl} FROM save_{t} WHERE slot=p_slot::int;")
    out.append("  -- Nothing half-finished from the old session may survive:")
    out.append("  -- these are rebuilt every tic and a stale row would fire.")
    for t in TRANSIENT:
        out.append(f"  DELETE FROM {t} WHERE map_id=target;")
    out.append("  -- Derived mirrors, rebuilt from the state just restored.")
    out.append("  doom_materialize_render_segs(target);")
    out.append("  doom_materialize_render_things(target);")
    out.append("  DELETE FROM sector_light_fx WHERE map_id=target;")
    out.append("""  INSERT INTO sector_light_fx
    (map_id, sector_id, special, base_light, dark_light)
  SELECT s.map_id, s.id, s.special::smallint,
         COALESCE(s.spawn_light_level, s.light_level)::smallint,
         LEAST(COALESCE(s.spawn_light_level, s.light_level),
               COALESCE(MIN(other.light_level), 0::smallint))::smallint
  FROM sectors s
  LEFT JOIN linedefs edge ON edge.map_id = s.map_id
  LEFT JOIN sidedefs r ON r.map_id = edge.map_id AND r.id = edge.right_sd_id
  LEFT JOIN sidedefs l ON l.map_id = edge.map_id AND l.id = edge.left_sd_id
  LEFT JOIN sectors other ON other.map_id = s.map_id
    AND other.id = CASE WHEN r.sector_id = s.id THEN l.sector_id
                        WHEN l.sector_id = s.id THEN r.sector_id END
  WHERE s.map_id = target AND s.special IN (1,2,3,8,12,13,17)
  GROUP BY s.map_id, s.id, s.special, s.spawn_light_level, s.light_level;""")
    out.append("}")
    out.append("return target;")
    out.append("$doom$;")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"  wrote {OUT}: {len(SAVED)} saved tables, "
          f"{sum(len(c) for c in cols.values())} columns")


if __name__ == "__main__":
    main()
